cyverse/atmosphere

- atmosphere/settings/__init__.py
This change finishes restoring the search and query capabilities of the v2 API.
1. Remove the rest_framework_filters backend (DRF extension) and replace with DRF's rest_framework.filter backend.
The rest_framework_filters backend is what was throwing the recent "no module named related".  The fix was made in their master branch (https://github.com/philipn/django-rest-framework-filters/commit/557ebdaf8a64bac7838900586f78cfc5583211b7) but hasn't been updated in their PiPy library through "pip install".
The DRF extension backend provides the ability to make API queries like "image__name__icontains=iplant", where as the standard DRF backend only provides the ability to query "image__name==iplant".
However, since we don't currently need (or expose) any query fields that provide that …
> replace rest_framework_filters with rest_framework.filters

- allocation/engine.py
- allocation/models/results.py
- allocation/tests.py
- core/models/group.py
- service/exceptions.py
- service/monitoring.py
As it turns out, - timedelta's are quite confusing to 'humans'..
For example, humans understand: 1 hour, 30 minutes OVER your allotted allocation.
Humans do NOT understand: -1 days, 22 hours, 30 minutes OVER your allotted allocation.
To remedy this, we treat timedeltas as a 'positive-only' value, accompanied by a 'is_over (allocation)' boolean value to indicate whether that time should be considered "The amount OVER allocation" or "The amount UNDER allocation"
> Refactor Allocation 'exception' message and - timedeltas

- service/tasks/driver.py
Added a 'fallback' when 'add_floating_ip' is called out of order by parsing the output of 'Bad Request' REST response from Neutron and making the appropriate call.
This edge-case can be encountered when re-activating very-old instances.
> Read the reason for 'bad request' on add floating IP and fix the problem (No Floating IP)

- api/v2/urls.py
- api/v2/views/__init__.py
- api/v2/views/metric.py
This PR is the backend compadre of [troposophere's instance_metrics component](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/104). It provides an api to fetch metrics against.
```
GET /api/v2/metrics/<Instance UUID>.json
GET /api/v2/metrics/<Instance UUID>.json?res=1&size=60&field=cpu&fun=perSecond
size: (number) 
datapoints to fetch
res: (number) 
minutes per datapoint
field: (string) "cpu" | "mem" | "rx" | "rw" 
type of metric to fetch
fun: (string) "perSecond" 
apply a time-based derivative to data
```
> Add proxy to graphite metrics

- api/v2/serializers/details/instance_history.py
- requirements.txt
Added 'image' and 'provider' to instance history to avoid deep-nested queries clientside. See https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/126 for details on how this changed the UI implementation.
> Add two more attributes to /v2/instance_history objects

- api/v2/views/image_version.py
- core/models/application_version.py
- core/models/instance.py
- core/models/machine.py
- core/query.py
- extras/init.d/atmosphere.uwsgi+nginx
- service/driver.py
- service/tasks/monitoring.py
For the incana-incana release..
use 'prune_machines' to end date images that have been deleted out of band.
use 'monitor_machines' to 'pull in' images that have been created out of band, and update sharing (both on the DB and on the cloud) to reflect the user's privacy choices.
> Include 'Monitor machines' as a periodic task

- api/v1/serializers/atmo_user_serializer.py
This change shouldn't have any negative effects on the code base. [Here](https://github.com/iPlantCollaborativeOpenSource/atmosphere/blob/bf8854654638a0e4473432087bf9d07475d1b65a/api/v1/views/profile.py#L45-L49) is the code that uses this modified serializer.
> A call to is_valid on a serializer shouldn't have side effects.

- service/instance.py
We are unable to stop running instances for the latest version of the Atmo API ([ATMO-1054](https://pods.iplantcollaborative.org/jira/browse/ATMO-1054)).
> Resolution for stop instances.

- api/v2/views/allocation.py
This is necessary for https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/193.
Creation of new allocation objects is necessary for assigning allocations that do not yet exist.
> Add POST to Allocation method list

- atmosphere/settings/local.py.j2
- core/models/user.py
Create a new setting to control whether or not the first identity should be auto-created for a user that has been deemed authorized into Atmosphere. This is a stop-gap measure, and this feature will be fleshed out at a later point in time to include which provider should/should not be used, what quota and allocation should be assigned to new users, etc.
> Include basic account bootstrapping for newly authenticated users.

- configure
Currently, the automation used via ansible has the limitation of an ASCII charset and the output from our enhanced scripts cause encoding failures. 
This removes the offending characters from the configure script.
> Avoided shallowing exception & opt for unicode output strings for enhanced output

- extras/nginx/Makefile.j2
This template for the extra nginx makefile has the old-style `generate_configs.py` for various targets. 
It also contained a copy-paste error for generating the nginx-jenkins and nginx load balancer.
> Altered template for nginx Makefile; correct copy-paste errors.

- extras/init.d/celeryd.default.dist.j2
- service/instance.py
The flower broker url is not what flowers like :tulip:. See @steve-gregory for a good reason why it breaks celery/flower.
The second small fix is for an incorrect error message.
> Small fixes

- service/tasks/monitoring.py
The exempt allocation list incorrectly contained allocations with threshold of -1, which was an empty list. This has been corrected to delta = -1, which will fix monthly allocation reset happening for users who should be exempt.
> fix typo in exempt allocation list

- api/v2/views/machine_request.py
Before creating a new machine request, check for currently open machine requests based on the same instance and raise and exception if any are found.
Redone from PR #75 to be targeted to Kicking Kestrel
> Avoid creation of multiple machine requests for the same instance

- api/v2/serializers/details/identity_membership.py
This is the intended fix that #82 was missing.  See #82.
> Added the hyperlink relation to the detail view for identity membership.

- api/v1/views/instance.py
When attaching to detach or attach (so, _instance actions_ associated with volumes), there is an error produced in the endpoint's response: 
At the heart of the error is that the object passed into the serializer is _actually_ a string presentation of a `Volume` model - and not valid JSON: 
```
... <Volume: 348b58a4-266b-4f01-93f8-91e437b588af> is not JSON serializable
```
It turns out that in refactoring the endpoints for the completion of work on _v2_, the following code from [](https://github.com/iPlantCollaborativeOpenSource/atmosphere/blob/incana-incana/api/v1/views/instance.py#L501-L508) got shift around. 
So in [`incana-incana`](https://github.com/iPlantCollaborativeOpenSource/atmosphere/blob/incana-incana/api/v1/views/instance.py#L501-L508), we handled _actions_ associated to …
> Fix response error encountered when attaching volumes. 

- api/permissions.py
- api/v1/views/profile.py
- api/v2/serializers/details/__init__.py
- api/v2/serializers/details/identity_membership.py
- api/v2/serializers/details/user.py
- api/v2/urls.py
- api/v2/views/base.py
- api/v2/views/user.py
- core/models/user.py
Give CloudAdministrators the ability to set 'is_staff', 'is_superuser', and activate/deactivate a user (By setting an end_date && marking 'is_active') on troposphere.
Users who login to troposphere after being deactivated will receive a banner message with related error message upon arriving at the 'Forbidden//No User' page.
[JIRA] (https://pods.iplantcollaborative.org/jira/browse/ATMO-979)
[Atmosphere PR] (https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/77)
[Troposphere PR] (https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/221)
> Allow CloudAdministrators to deactivate Atmosphere Users

- api/base/views.py
- api/v1/urls.py
- api/v1/views/__init__.py
- api/v2/urls.py
[JIRA] (https://pods.iplantcollaborative.org/jira/browse/ATMO-606).
[Troposphere PR] (https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/216).
Adds a 'Version' (for Atmosphere) and DeployVersion (for atmosphere-ansible) that can be queried to help the end user find out what SHA the current API is based from.
> Create a base viewset for both APIs (Version, DeployVersion)

- api/v2/views/machine_request.py
Setting `old_status` to `"processing"` in the machine_request view was causing issues with the handling of Image Requests ([ATMO-1104](https://pods.iplantcollaborative.org/jira/browse/ATMO-1104)). By removing this initial value for `old_status`, the value is set based on the default (depending on if the deployment is _auto-imaging_ or not). 
See [ATMO-1104](https://pods.iplantcollaborative.org/jira/browse/ATMO-1104) for more details.
> Fix - Removed `old_status` initial value from machine_request view.

- api/email.py
- api/exceptions.py
- api/v1/views/hypervisor.py
- api/v1/views/identity.py
- api/v1/views/instance.py
- api/v1/views/machine.py
- api/v1/views/meta.py
- api/v1/views/occupancy.py
- api/v1/views/size.py
- api/v1/views/volume.py
- api/v2/views/instance.py
- api/v2/views/volume.py
- core/exceptions.py
- service/driver.py
[JIRA] (https://pods.iplantcollaborative.org/jira/browse/ATMO-782)
When a provider is marked inactive, let the user know via a non-200 API status code with a descriptive error message: `Cannot create driver on an inactive provider: iPlant Workshop Cloud - Tucson`
Providers are 'inactive'  when they have reached their `end_date` or when the `is_active` flag is toggled off.
> Respond with 409 and inform user when a Provider is Inactive

- api/v2/serializers/details/resource_request.py
- api/v2/views/base.py
- api/v2/views/resource_request.py
- core/models/abstract.py
Allow users to close their own resource requests.
This is done by end dating resource requests when a PATCH is made to the resource_requests endpoint with a status of "closed." 
An end dated request also allows a user to make another request without their old request needing to be fully deleted from the database.
> End date resource requests

- api/v1/views/machine.py
Addresses ATMO-976
Return invalid_provider_identity when an identity doesn't exist on a provider. Previously returned an HTML response to a serializer that caused DRF issue.
> Raise v1 machine exception

- api/v2/serializers/details/volume.py
- api/v2/views/volume.py
- requirements.txt
- service/volume.py
The perform_create and perform_delete methods, previously, were pointing to bad functions and variable names. As well, some variables were being requested that were not necessary for CREATE. All of these errors have been fixed. Description is now a passable kwarg when POSTing to volume.
An update to rtwo (0.2.18) was required to move forward.
I did test creating volumes with image_id and was unable to perform the action on OpenStack Havana. We can revisit why Images aren't being copied into Volumes when we are running a later version of OStack.
> Fix API v2 /volume POST and DELETE methods

- api/v1/views/instance.py
- service/exceptions.py
- service/task.py
Addresses ATMO-1141
When attempting to delete an instance that no longer exists, raise 404 error with descriptive error. 
Previously, there were checks in all instance actions **except** the delete action to see if the instance exists before continuing.
This PR adds that check before deleting an instance, and fixes an error in the exception that was being raised in all other actions in the case of a nonexistent instance. 
Here is a timeline of the original error returned by the API when deleting a nonexistent instance to the current error being returned.
> Fix instance deleted

- core/email.py
When shifting to the API v2 `email_support` endpoint, I get an error regarding an unexpected keyword argument, `data`:
It turns out the source of the error is a call to `email_admin` in the email view for `api/v2`:
```python
email_success = email_admin(
self.request, subject, message, data=data)
```
source: [api/v2/views/email.py](https://github.com/iPlantCollaborativeOpenSource/atmosphere/blob/kicking-kestrel/api/v2/views/email.py#L54-L62)
After popping off the required `subject` & `message` keys, we're trying to easily pass along any additional information that the UI provided as part of "extra data" in the message. 
But, `email_admin` doesn't expect this:
```python
def email_admin(request, subject, message,
cc_user=True, request_tracker=False):
```
source: …
> API v2 fix email support keyword arg

- api/v2/serializers/details/image_version.py
- core/models/application.py
- core/models/application_version.py
- service/instance.py
Addresses ATMO-1138
Allow users to update minimum requirements of the images they own.
Users can update either min_cpu or min_mem or both, and both will default to 0 if no value is given.
CPU is currently limited to positive integers less than 16, and memory is limited to positive integers less than 32 * 1024 (32 GB).
> Update image version

- api/v2/views/base.py
- api/v2/views/resource_request.py
- core/email.py
- core/models/abstract.py
If an `admin_url` parameter is passed in a POST to create a resource request, change the admin URL emailed to administrators to respect it. This is done by taking the base admin URL given by the client, and appending the ID of the newly created request to it.
If an `admin_url` parameter does not exist, continue sending the current Django admin link.
> Respect admin_url parameter for resource admin emails

- api/v2/views/machine_request.py
Add function called when `request.is_closed()` is true. Currently has no functionality, but prevents an error from being thrown when an imaging request is denied.
> Add close action to machine request

- api/v2/views/machine_request.py
- service/machine.py
If an image is private, share the image with the user and admins by default. Also remove duplicate usernames from access list.
> Default private access list

- core/models/boot_script.py
- core/templates/scripts/bash_inject_env.sh
- service/deploy.py
- service/instance.py
- service/licensing.py
- service/task.py
- service/tasks/driver.py
This first PR include support for a single variable, $ATMO_USER that represents the user of the identity that created the instance.
Any other variables injected should also carry the $ATMO_ namespace.
Scripts that execute after this should be expected to "source the file $HOME/.bashrc for the deploying user (Usually root)".
A later version would ideally have ansible support. Will consult with @amercer1 about development on this front.
This will be patched into production to help a user get their image up and running properly.
> Update user boot scripts deployment to include injection of $ATMO_ variables

- core/models/application.py
- core/models/application_version.py
- core/query.py
- service/tasks/monitoring.py
Fix for ATMO-1114
Fixed prune machines so that it will prune invalid Apps, Versions and ProviderMachines based on cloud *and* database values.
Added some convenience methods for `end_date_all()` and `_current_versions()`
> Fix periodic task 'prune_machines'

- api/v2/views/instance_history.py
We currently treat "instance status history" as an instance launch history in Troposphere, displaying the list as a list of the instances you've launched.
This list is actually a list of all instance statuses, meaning one instance has multiple entries in the list, which goes against how we've been using it.
This PR allows for filtering `unique=True` to get a list with unique instance IDs, effectively giving us a list of the instances a user has launched.
> Add filtering to instance status history

- api/status/urls.py
- api/status/views/__init__.py
- api/status/views/celery.py
- api/urls.py
- requirements.txt
- service/deploy.py
Endpoint was created at the request of QA, who would like to determine if celery is running prior to executing API tests.
If celery is running, the API returns:
```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"status": 200,
"message": "Celery is running"
}
```
If celery is NOT running, the API returns:
```
HTTP 404 Not Found
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"status": 404,
"message": "Celery is NOT running"
}
```
> Include new endpoint `/api/status/celery`

- api/v2/serializers/details/image_version.py
- api/v2/views/provider_machine.py
- core/models/application.py
- core/query.py
- requirements.txt
Filter displayed machines an image version is available on, based on whether or not the user has access to the cloud the provider machine exists on.
This is done for the ProviderMachine viewset itself, and the nested `machines` field within an image version.
> Filter image version machines

- api/v2/views/maintenance_record.py
- api/v2/views/project.py
Don't allow API deletion of a Project until all Project Resources (Including newly-added External Links and Applications/Images) are moved out of the project.
> Update delete project requirements

- core/models/allocation_strategy.py
- core/models/quota.py
Some of the Django ORM code was trying to cast the callable 'default' functions to 'int'. Probably because the more recent ORM code assumes that arguments to queryset methods can't be callable.
I couldn't find anywhere where my change should be a problem, but somebody had better check my assumption.
See:
- <https://github.com/django/django/pull/2091>
- <https://code.djangoproject.com/ticket/11629>
> Fixed a bug with default Quotas and Allocations.

- api/v2/views/machine_request.py
If `?active=true` when retrieving machine requests, only display requests that are currently pending or have been created in the past 7 days.
> Add machine request filtering

- core/templates/core/email/feedback.html
Just a simple template change. RT tries to interpret the `Name:` header as a command.
When this gets merged, I'll cherry into NN.
> Remove 'Name:' which gets interpretted by RT as command

- core/email.py
This reverts the admin url. Now it points to the admin panel for identity memberships.
> Revert tropo admin url

- allocation/models/inputs.py
- allocation/models/strategy.py
- api/v2/serializers/details/instance.py
- api/v2/serializers/details/instance_history.py
- core/models/allocation_strategy.py
- core/models/identity.py
- core/models/instance.py
- core/models/instance_history.py
- core/models/provider.py
- service/monitoring.py
Also, allow Allocation calculation per provider, per instance, & per history/status update.
Will cherry-pick to `n-n` after release.
> Use 'proper' method for calculating total_hours

- api/v2/serializers/summaries/quota.py
- atmosphere/settings/local.py.j2
When changing the templates, it seems we unfairly grouped `AuthTokenLoginBackend` as a 'globus-only' requirement..
> Update settings to allow emulation by AuthToken

- service/instance.py
Added missing `provider` parameter for the `update_metadata` task.
> [ATMO-1367] Task remove_ips fails

- extras/nginx/site.conf.j2
- variables.ini.dist
Uses a variable, `ENABLE_HTTP2`, within `[nginx]` section to alter the `site.conf` produced. 
See [ATMO-1372](https://pods.iplantcollaborative.org/jira/browse/ATMO-1372)
> Enable HTTP/2 module in Nginx site configuration

- README.md
- contrib/migrations-warning.rb
- contrib/post-merge.hook
- contrib/requirements-warning.rb
This includes some hooks that are run when the user pulls from master (more
specifically any merge). They comment when there are changes made to
requirements.txt or when migration files are added.
For example:
[requirements-warning.rb hook]: New python requirements.
pip install dev_requirements.txt requirements.txt
[migrations-warning.rb hook]: New migrations found.
./manage.py migrate
> Add warning hooks

- api/v1/views/volume.py
- api/v2/serializers/details/volume.py
- api/v2/serializers/post/__init__.py
- api/v2/serializers/post/volume.py
- api/v2/views/volume.py
- core/models/project.py
- core/models/volume.py
- service/volume.py
[x] - Updated the `create_volume_or_fail` method to return a core object
rather than a cloud object.
[x] - Update v1 API to call `create_esh_volume`
[x] - v2 API serializer now has a POST Serializer, and swaps serializers
before returning the value.
[x] - Project appends volume at the end, it cannot be added in the save()
method.
> Atmo 1369 assign project on v2 create volume

- requirements.txt
Relates to feedback from [Clank Issue 63](https://github.com/iPlantCollaborativeOpenSource/clank/issues/63) where the uWSGI 2.0.9 on Ubuntu 16.04 encounters a compile on `pip install`. 
This will require verification in the `dev` environment. A merge into dev can be verified using the QA regression tests, both API & QA.
> Update uWSGI dependency version

- scripts/add_new_provider.py
Since 0241751155e8d5269a2c188ff4b54435bc0aa5f6, the return of validate_answer is expected to be a validated answer (not simply `True`/`False`). This change updates the lambdas to meet that expectation.
Otherwise, adding a provider fails by setting validated values like Provider.virtualization to `True`:
```
Traceback (most recent call last):
File "./scripts/add_new_provider.py", line 356, in <module>
main()
File "./scripts/add_new_provider.py", line 350, in main
new_provider = create_provider(provider_info)
File "./scripts/add_new_provider.py", line 296, in create_provider
type=provider_info["type"], public=False)
File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File …
```
> Fixes lamba validators in add_new_provider.py

- extras/nginx/Makefile.j2
- extras/nginx/locations/lb.conf.j2
- variables.ini.dist
The Leaderboard interactive visualization is no longer part of the default Atmosphere login page. Since it is not seen, this location needs to be removed.
> Remove leaderboard nginx location

- atmosphere/settings/__init__.py
- atmosphere/settings/local.py.j2
When upgrading from Django 1.8 to 1.9, there were [changes to the definition of settings.TEMPLATES](https://docs.djangoproject.com/en/1.9/ref/templates/upgrading/). The presence of `TEMPLATE_DEBUG` will cause a warning to generated (this will happen in atmosphere upon `service atmosphere start`). A similar PR was submitted to troposphere (as [Troposphere PR 403](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/403)).
The warning message can be produced by doing a `check`:
```
09:59 $ ./manage.py check 
System check identified some issues:
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG. …
```
> Updated Django template backend definitions

- core/templates/core/email/feedback.html
- core/templates/core/email/instance_report.html
- core/templates/core/email/volume_report.html
TLDR: let the email ticket system be responsible for sanitizing support emails
By default django auto-escapes all templates. You have to mark something as
safe for it to be not escaped. Our issue is that django was escaping html,
and then RT escaped the escaped content!
> Fix templates for support to allow quotes, brackets, etc.

- api/v2/views/base.py
Authors of Machine/Resource Requests should now be able to close their own requests within the API.
(NOTE: Intentionally 'closes' the request, rather than delete.)
REF: [JIRA](https://pods.iplantcollaborative.org/jira/browse/ATMO-1408)
> Allow user to 'complete the loop' and close their own Requests

- allocation/tests.py
- api/tests/test_auth.py
- core/tests/instance.py
- core/tests/machine_request.py
This resolves an import failure generated while attempting to run unit tests. 
In Django 1.9, [`django.utils.unittest` was removed](http://django.readthedocs.io/en/latest/internals/deprecation.html#deprecation-removed-in-1-9).
The deprecation announcement in Django provided some context on how to handle the situation:
> `django.utils.unittest` provided uniform access to the `unittest2` library on all Python 
> versions. Since `unittest2` became the standard library’s `unittest` module in Python 
> 2.7, and Django 1.7 drops support for older Python versions, this module isn’t useful 
> anymore. It has been deprecated. Use `unittest` instead.
source: http://django.readthedocs.io/en/latest/releases/1.7.html#django-utils-unittest
I've made 4 changes and opted for continuing to use `unittest` …
> Resolved import failures for tests

- service/networking.py
changed `router.name` to `router['name'] `
changed `network.name` to `network['name']` 
in `service/networking.py`
> fix "dict has no attr. 'name'" error

- api/v2/views/identity.py
- core/management/commands/export_identity.py
- core/models/identity.py
- service/accounts/openstack_manager.py
- service/openstack.py
Example command:
`./manage.py export_identity --identity-id ## --filename /path/to/file`
I realize that `identity_id` is not the easiest thing to come by, but this solution can be used now to address the needs of our external deployers and testers.
> Add new API and management commands to export an identity

- api/v2/serializers/details/tag.py
- api/v2/serializers/summaries/tag.py
- api/v2/views/machine_request.py
- atmosphere/settings/__init__.py
- core/models/tag.py
- core/models/user.py
Rather than introduce more database migrations, this is a simple approach that will allow the Troposphere UI to block users from submitting tags that are reserved for staff users *only*.
[Depends-on-Troposphere PR](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/435)
> Create a setting to blacklist tags

- atmosphere/settings/__init__.py
- core/hooks/allocation_source.py
- core/models/allocation_source.py
- core/models/event_table.py
- service/monitoring.py
- service/tasks/monitoring.py
- Disables 'monitor_instance_allocations'
- New hook listens on AllocationSourceSnapshot. If the compute is >100%, enforce allocations (once, and note it in the event, and ignore it for all future calls where compute is >100%)
- Run the enforcement task Asynchronously so that users are not "stuck inside the hook"
- Move from `pre_save` to `post_save` for `listen_before_allocation_snapshot_changes`
> Enforce allocation sources

- service/tasks/driver.py
A user's instance was stuck in "active-deploying". After several re-deploys, I looked into the culprit. The instance deploy task will retry until it fails. Once it fails we call another task to update the instance with status "error-deploy error". That second task was never called.
It turns out that if the time limit is exceeded (while it's retrying) the first task is terminated and the second is never run. By using a soft time limit, the second will get a chance to do cleanup, if a timeout occurs.
I verified that this was indeed the culprit by testing very small time_limits and small soft_time_limits to compare.
> Fix instance hung indefinitely in active deploy

- core/tests/models/test_event_table.py
- jetstream/test_tas_api.py
Solution: A. Skip Jetstream tests if the 'jetstream' app is not enabled, and B. override the allocation source warning thresholds to work with the EventTable test logic.
> Problem: Jetstream and EventTable tests fail with default settings

- contrib/requirements-warning.rb
Only `nil` and only `false` are falsy in ruby. I made the mistake of thinking the empty string was falsy.
Now the hook should only speak up when it's supposed to!
> Fix requirements hook falsy test

- api/v2/serializers/post/instance.py
…  until CyVerse has fully integrated with the feature.
> Do not require 'allocation_source_id' for /v2/instances

- service/deploy.py
... as a result of an invalid `playbook_dir` _OR_ an invalid `limit_playbooks` argument.
> Add AnsibleDeployException when zero playbooks are available

- api/pagination.py
- api/renderers.py
- api/v2/serializers/details/__init__.py
- api/v2/serializers/details/reporting.py
- api/v2/urls.py
- api/v2/views/__init__.py
- api/v2/views/emulate.py
- api/v2/views/reporting.py
- requirements.txt
- service/instance.py
> Instance reporting by API

- api/v2/views/image.py
- core/models/application.py
- core/query.py
There was an exponential slowdown when a user searched for images. Without getting into the details `filter(testA).filter(testB).filter(testC)` can result in very very bad sql. django-rest-framework was doing this and we were as well. The solution is to use `filter(testA & testB & testC)`. Rather than wait for drf to fix this issue, we have monkey patched the troublesome method (when they release a fix, we'll revert the patch).
Read a ticket I filed against Django:
https://code.djangoproject.com/ticket/27388
Here is a general thread:
https://code.djangoproject.com/ticket/27303
Here is a rough estimate of the performance for the underlying sql, based on the number of terms in a search.
```
===================
1          0.047
2          0.056
3          0.066
4          0.076
5 …
```
> Fix search 🎉 

- atmosphere/settings/local.py.j2
Solution: Disable database serialization. We don't need it, and it slows things down. See: https://docs.djangoproject.com/en/1.10/ref/settings/#serialize
> Problem: Atmosphere Django tests are slow

- jetstream/tasks.py
Solution: We should be treating TAS as the source of truth, instead of calculating it ourselves.
- Integrated and refactored @amit4111989's code for using the TAS API as source of truth
- I have some offline tests with production data which give me confidence in these new calculations, but I would still like to create tests using test data
- Modified signature of `update_snapshot` so I can pass in start & end dates
TODO:
- Corrective reports
- Tests with clean test data
> Problem: Jetstream allocation source usage appears too high

- jetstream/tasks.py
- service/allocation_logic.py
Problem: Jetstream allocation source burn rate appears high
Solution: Re-calculate burn rate per user/allocation/instance.
I misunderstood the burn rate column in the report rows. It was returning the cumulative burn rate. I added a separate calculation.
> Faster update snapshot hotfix burn rate

- core/models/quota.py
Creating a volume threw an api error because it would check a user's quota.
This fixes get_quota for an identity.
> Change old reference from quota.identitymembership to quota.identity

- service/tasks/volume.py
It looks like the `instance` variable was removed during an extract
method refactor, but the later exception handling code was not tweaked.
Amit (@amit4111989) & I discovered this while triaging an issue with Volume attachment.
> Correct variable name to one within scope

- .gitignore
- extras/nginx/Makefile.j2
- extras/nginx/locations/flower.conf
- extras/nginx/locations/jenkins.conf
- variables_templates.json
Nginx was failing, it's configtest was not passing. The reason was because the
server specified in the proxy_pass directive was not resolving. Nginx checks
these beforehand to help. Nginx cannot resolve SERVER_URL (i.e.
app.atmo.cloud) so it fails. The solution is to use localhost.
> Fix proxy pass so ngnix server starts

- api/v2/views/email.py
- core/templates/core/email/feedback.html
- core/templates/core/email/instance_report.html
- core/templates/core/email/volume_report.html
When I deal with a ticket its not helpful for me to have the provider uuid, i need to know at a glance the location (Tucson vs Workshop). 
@steve-gregory Do you ever need the uuid?
> Prefer provider location rather than uuid in support emails

- service/networking.py
Subnet creation will allow for conflicts in the subnet that turn into errors down the road. Actively search for and avoid CIDR conflicts
> Bugfix: CIDR conflicts during subnet creation

- extras/nginx/locations/flower.conf
Proxy_pass defines a uri for some proxied resource. If the uri contains a
variable nginx applies special rules. A resolver must be defined. We use
google's 8.8.8.8 dns. We used to use SERVER_NAME in the uri for the
resource, this works for productions servers with dns entries but fails for
local machines.
This solution removed the variables that were unnecessary and removed any
hostname that would need to be resolved.
I tested this on a production server with dns resolution, on a vm without dns, and I tested on my vm with app.atmo.cloud (since nginx special cases hostname ending in .dev).
> Fix nginx proxy pass unable to resolve localhost

- service/tasks/driver.py
Currently, it doesn't know whether the floating ip has been using by another instance or not. Not necessarily to add this specific condition. 
Thanks
Lucas
> add extra condition for resue free floating ip

- core/models/application.py
- core/models/machine.py
- service/tasks/monitoring.py
... due to attr lookup on glance_image. Solution: use `owner` if its
available for the image otherwise use `application_owner`.
> Hotfix for monitor_machines_for which is failing

- api/v1/views/machine_request.py
- core/models/machine.py
- service/accounts/openstack_manager.py
The situation occurs when new glance images are found that represent **the second version** of an application that has been replicated across providers via an external process. These images were an unexpected edge case because the image ID is *not* the same image that created the *application UUID*, and so the logic (Testing image ID against application UUID) that blocks externally-created-images from being incorrectly ingested as atmosphere was *also* blocking these version from correctly setting the application kwargs, potentially allowing this version to create a new image. 
Instead, if REPLICATION_PROVIDER_LOCATION is set (redefined 'set' as getattr, not hasattr) attempt to find a similar image that already exists in the stack, and use its application to define yourself.
> Problem: new versions of image fall through logic-cracks

- api/renderers.py
- api/v2/views/reporting.py
Solution:
- Allow `filename` as a query_param on the request
- Respect `filename` by saving headers to the DRF Response, *NOT*
`StreamingHTTPResponse`
> Problem: Reporting api saves all files as reporting.xlsx

- extras/logrotate.atmosphere
- extras/logrotate.celery
Current logrotate file naming convention is not conducive to archiving.
Add a date to the end of the rotated files. (`dateext` option)
refs [#ATMO-1682](https://pods.iplantcollaborative.org/jira/browse/ATMO-1682)
> Use date extension file naming for logrotate for easy archiving.

- api/v2/serializers/post/instance.py
- api/v2/views/instance.py
- core/models/user.py
Solution: Fix /api/v2/instances POST to properly set 'project' after instance launch, but before returning/serializing data for the user.
> Problem: Instance launch via /api/v2/instances ignore 'project'

- api/v2/views/image.py
- Include the ability to include `?featured=true` to return only featured applications.
- Include default ordering to drop end-dated results to the bottom of the page, and then sort chronologically (with newest images showing up first).
> v2 Image API improvements

- core/management/commands/find_uuid.py
- core/models/instance_source.py
**Huge shoutout to @amit4111989 for figuring out how to make this happen in Django!**
A common support use-case is that you are given a UUID without a whole lot of context. This PR creates a management command `./manage.py find_uuid` that will allow you to gather additional context, quickly, from the command line.
Examples:
```
/opt/dev/atmosphere# ./manage.py find_uuid '11223344-07a2-4e22-ae52-a61e87155c1f'
String <11223344-07a2-4e22-ae52-a61e87155c1f> belongs to <class 'core.models.volume.Volume'> 11223344-07a2-4e22-ae52-a61e87155c1f
/opt/dev/atmosphere# ./manage.py find_uuid '12345678-ef90-48ec-9be0-1b2ca71ee8c8'
UUID <12345678-ef90-48ec-9be0-1b2ca71ee8c8> belongs to <class 'core.models.provider.Provider'> 6:iPlant Cloud - Austin
```
> Create new management command: find_uuid

- extras/logrotate.atmosphere
- extras/logrotate.celery
Problem: Getting error messages like this:
```
error: error opening /var/log/celery/atmosphere-deploy_7.log: Permission denied
```
Solution: Change the structure of the logrotate config files back to what they
were and just have the `dateext` line added.
> Fix logrotate permissions error

- service/tasks/driver.py
- service/tasks/machine.py
- Include ability to test 'tmp_status' to hold 'wait_for' task until its
truly ready.
- Update the validate step to return instance *alias* not *database id*
- Verified that validation holds until instance deployment
- Verified that instance is destroyed post-validation-success.
modified:   service/tasks/driver.py
modified:   service/tasks/machine.py
Note: Video only shows the task name to avoid showing flower's `args` column
> Working example of image validation

- requirements.txt
- service/accounts/openstack_manager.py
Fix rtwo, chromogenic, and the args that are used to instantiate the two to provide the expected parameters for keystoneauth.
This new method should avoid "Bad service catalogs" when creating drivers as the admin/user, and avoid `404 Endpoint not found` errors that were being found in the current release of Atmosphere.
> Problem: using deprecated method for creating keystoneclient

- atmosphere/celery_init.py
- service/accounts/openstack_manager.py
- Selecting specific loggers, prior to using them, and forcing their log level to respect `DEP_LOGGING_LEVEL` in atmosphere.
- Colorized output in celery (Not required, but expected for future versions of celery initialization).
> Problem: In some conditions, The logfiles are growing at a high rate

- atmosphere/plugins/auth/expiration.py
- atmosphere/settings/local.py.j2
- variables.ini.dist
If the following line is added to variables.ini:
EXPIRATION_PLUGINS = ['atmosphere.plugins.auth.expiration.LDAPPasswordExpired']
Then whenever an LDAP password expires, the AtmosphereUser will have:
{
...
is_expired=True
...
}
The UI can leverage this state, to prevent instance launches and provide
feedback.
I tested this with ldap enabled an an expired password, and confirmed the ui showed the updated warnings.
I tested the updated clank variables and deployed against a vm.
See https://github.com/cyverse/troposphere/pull/555 for the tropo component.
> Enable expiration plugins so that ldap expiration surfaces

- api/v2/views/email.py
Problem: Instance report email shows wrong provider
Solution: Get the provider from the instance instead of the
`user.selected_identity.provider`
refs [#ATMO-1744](https://pods.iplantcollaborative.org/jira/browse/ATMO-1774)
~~- [ ] New test(s) included to reproduce the bug/verify the feature~~
~~- [ ] Documentation created/updated at [Example link to documentation]~~(https://example.test/doc#new_section) to give context to the feature
~~- [ ] If necessary, include a snippet in CHANGELOG.md~~
> Problem: Instance report email shows wrong provider

- api/tests/v2/test_image_metrics.py
Problem: Typo in variable
Solution: Change `build` to `self.status_build`
Note: This test still breaks, but I'm not sure why. See #294
~~- [ ] New test(s) included to reproduce the bug/verify the feature~~
~~- [ ] If necessary, include a snippet in CHANGELOG.md~~
> Problem: Typo in variable

- core/models/user.py
- service/accounts/openstack_manager.py
- service/exceptions.py
##Solution:
raise AccountCreationConflict when 'unauthorized' errors prevent new accounts from being created.
> Problem: Account creation errors can go undiagnosed

- atmosphere/settings/local.py.j2
- core/models/machine_request.py
- service/accounts/openstack_manager.py
- service/machine.py
These unstaged changes were on the jetstream server and should be included before the next release.
**Highlights:**
- Bugfix: Include domain_name for non-2.0 password auth (on openstack clouds)
- Internal: Increase time limit and duration for allocation monitoring tasks.
- Bugfix: Updated 'share_image' to pass Identity (for all credentials) rather than just project_name.
> Small updates from the Jetstream server

- service/deploy.py
- service/instance.py
- service/task.py
- service/tasks/volume.py
https://github.com/cyverse/atmosphere-ansible/pull/79
> Remove ScriptDeployment from mount_volume tasks

- core/migrations/0079_add_events_for_old_allocationsource.py
... problem occurs when 'jetstream' is not in INSTALLED_APPS.
Avoid RuntimeError by checking if jetstream is in INSTALLED_APPS and skipping the migration.
(Can be verified by successful travis run)
> Problem: Latest migration can result in RuntimeError

- core/models/size.py
- requirements.txt
- service/tasks/monitoring.py
- It turns out openstack will show disabled sizes if you query for
them explicitly. The latest version of rtwo will enable you to
force lookups on sizes and re-name Unknown sizes as part of the
'monitor_sizes' periodic task.
```
>> from core.models import Size
>> unknown_sizes = Size.objects.filter(name__contains='Unknown Size')
>> unknown_sizes.count()
8
>> from service.tasks.monitoring import monitor_sizes_for
>> monitor_sizes_for(5)
>> unknown_sizes = Size.objects.filter(name__contains='Unknown Size')
>> unknown_sizes.count()
2
```
> Problem: 'Unknown Sizes' appear when sizes are disabled

- atmosphere/celery_init.py
Solution:
- Include in file `atmosphere.celery_init` the celery setting `app.conf.beat_schedule`
> Problem: Celerybeat schedule not properly imported

- api/tests/factories/__init__.py
- api/tests/factories/allocation_source_factory.py
- api/tests/v2/test_allocation_sources.py
- api/v2/views/allocation_source.py
Problem: Searching and retrieving Allocation Sources via the API fails.
Solution: Fixed search and lookup fields and added some tests.
TODO: There is one test (retrieve/details) which fails for some reason.
> Problem: Searching and retrieving Allocation Sources via the API fails.

- CHANGELOG.md
- requirements.in
- requirements.txt
- scripts/application_to_provider.py
This PR adds support for image data transfer via iRODS data object copy, when both the source and destination providers both use the [iRODS storage back-end for Glance](https://github.com/cyverse/glance-irods), and both providers share a common iRODS zone. Very specific to CyVerse atmosphere(0) and perhaps not likely that anyone else will use it! The benefit for us is that migrating images becomes very fast, on the order of a minute rather than 10-30+ minutes.
Using iRODS to transfer image data requires us to reach "around" the Glance API, populating the image data in iRODS out-of-band, and then adding the location to the image object in the Glance API. Unfortunately, using Glance in this way has some caveats:
- Glance does not allow adding a location to an image unless we enable a …
> iRODS transfer support for application_to_provider

- jetstream/features/steps/tas_api_steps.py
- jetstream/models.py
- jetstream/tasks.py
Problem: `behave` tests fail when not `settings.USE_ALLOCATION_SOURCE`
Solution:
- Tweaked tests and Jetstream allocation tasks
- Jetstream now uses allocations by default
- There was also a missing `app_label` on `TASAllocationReport` model
Fix #331
~- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~
~- [ ] If necessary, include a snippet in CHANGELOG.md~
> Problem: `behave` tests fail when not `settings.USE_ALLOCATION_SOURCE`

- scripts/application_to_provider.py
Problem: application_tags Glance metadata field was not populated with valid JSON
Solution: `json.dumps()` the app_tags list when setting application_tags in Glance image
Tested this and confirmed that now application_tags is set properly in Glance:
`application_tags='["bioconductor", "R", "Ubuntu", "edgeR", "RStudio", "base", "ggplot2", "ubuntu1404", "xfce"]'`
> Populate Glance image metadata application_tags with valid JSON

- api/v2/serializers/details/instance.py
- api/v2/serializers/summaries/instance.py
- core/models/instance.py
- core/models/machine.py
- core/models/volume.py
- requirements.txt
- service/instance.py
- service/tasks/monitoring.py
- service/volume.py
Improve the "Bootable volume" support for Atmosphere monitoring
- Monitor instances no longer fails when bootable volume encountered
- Monitoring tasks return all converted cloud resources
- Created one `monitor_resources` monitoring task to rule them all
- APIs wont fail when volume is encountered, No errors encountered in troposphere after API failures resolved.
- Update requirements.txt to latest version of rtwo **REQUIRED**
> Problem: Bootable volumes caused errors in API and Monitoring 

- core/migrations/0071_provider_more_instance_actions.py
Include the 'redeploy' key in the migration. 
Have you already applied this migration? Go ahead and run these lines:
```
from core.models import InstanceAction
action = InstanceAction.objects.get(name='Redeploy')
action.key = 'Redeploy'
action.save()
```
> Problem: 'Redeploy' InstanceAction created incorrectly in migrations

- core/models/instance_action.py
When an instance is `shelved_offloaded`, the user interface (Troposphere) cannot perform actions on it. 
Solution - Handle both "shelved" & "shelved_offloaded"
It seems that an instance that has been "shelved" will appear as being "shelved", then after a time (which is configurable) will transition to "shelved_offlanded".  Both states can be handled with the same mapped instance-actions.
> Problem: shelved instances become shelved_offload and UI cannot act on them

- jetstream/features/create_report_test_after_user_deleted.feature
- jetstream/features/steps/create_report_test_after_user_deleted.py
- jetstream/tasks.py
.When user is deleted while querying TASApi and before update_snapshot is run, their usage (although negligible) will be ignored. Fix in the TASAllocationReport creation logic takes care of that.
There are tests included with feature - create_report_test_after_user_deleted, which verify that the improvement works as expected and performs calculations correctly
> Atmo 1854 : TASAllocationReport creation for deleted user's unaccounted allocation usage

- core/models/instance_action.py
In the current documentation for Jetstream, authoring an Image while an
instance is in Active or Stopped state is _encouraged_ [\[0\]](https://iujetstream.atlassian.net/wiki/display/JWT/Customizing+and+saving+a+VM). However, we
currently only offer "Start" along with **basic** actions for a shutoff
instance [\[1\]](https://iujetstream.atlassian.net/browse/JETSTREAM-149).
[0] https://iujetstream.atlassian.net/wiki/display/JWT/Customizing+and+saving+a+VM
[1] https://iujetstream.atlassian.net/browse/JETSTREAM-149
> Problem: "Image" is not an availalbe action for shutoff instances

- core/models/instance_action.py
Since taking a snapshot of an instance as an image and storing it in `glance` is _part_ of the shelving process then allow "Image" as a valid action.
> Problem: cannot author images of shelved instances

- scripts/application_to_provider.py
`--clean` argument uses Chromogenic library to remove undesired state from images which were created from Atmosphere(1) instances. Uses `mount_and_clean()` function of Chromogenic library. Resolves [ATMO-1843](https://pods.iplantcollaborative.org/jira/browse/ATMO-1843) and moves toward resolution of [ATMO-1825](https://pods.iplantcollaborative.org/jira/browse/ATMO-1825).
Also, when we decide whether to attempt migrating image data between providers, we'll now use image status in the destination provider (rather than size/checksum) to determine if Glance will allow image data upload (i.e. status is "queued"). If Glance image is already in active status, we compare sizes/checksums and log a warning if they don't match (though this may be expected in some cases).
- New feature documented in …
> application_to_provider.py cleans images with Chromogenic

- service/exceptions.py
- service/tests/test_exceptions.py
Problem: DeviceBusyException method references uninitialized attribute
This caused an exception when printing the exception. Very meta.
Solution: Set the missing attribute (`process_list`)
Fixes #360
> Problem: DeviceBusyException method references uninitialized attribute

- core/query.py
Specifically, the only_current queries related to Instance.
In the future, we may move to less restrictive queries
_for all_ cloud resources, to avoid 'time sync' errors/issues
> Changing  `only_current` query for `start_date` to be less restrictive (for Instances)

- features/allocation.features/alternate_story.feature
- features/steps/allocation_story_steps.py
- service/allocation_logic.py
'instance_allocation_source_changed' event is fired before any instance status history is created which results in 0 usage for new instances
> ATMO-1910 : Allocation usage not counted for new instances

- cyverse_allocation/tasks.py
- features/allocation.features/alternate_story.feature
- features/steps/allocation_story_steps.py
- service/accounts/openstack_manager.py
- Missing self argument from function calls
- Added a task for one-time renewal of allocation sources without the rules engine
* note - this one-off renewal retains any changes in compute_allowed thus saving us the trouble of increasing compute allowed again for users
- Tests and their implementation added to make sure the changes work as expected
> Bug with creating allocation source for new user fixed + Task for one-off renewal of Allocation Sources

- service/instance.py
Simple fix. The `_token_to_keystone_scoped_project` used in the L1584 never got imported.
> Add a missing lib used in user_driver

- atmosphere/settings/__init__.py
- jetstream/allocation.py
- jetstream/models.py
- jetstream/tas_api.py
- jetstream/tasks.py
- requirements.in
- requirements.txt
Problem: Generating & sending TAS Allocation Reports is slow.
Solution: Use a few different approaches to speed it up
- Only send reports with non-zero `compute_used`
- Use `django-memoize` to add a cache with a 5 minute timeout for all TAS API `GET` requests
- Use `MAX` aggregation to find last report date, instead of listing all reports by `end_date` and then grabbing the last one.
> Problem: TAS reports are slow

- atmosphere/settings/local.py.j2
- service/monitoring.py
- service/tasks/monitoring.py
Problem: Wrong parameter for enforcement function
`allocation_source_overage_enforcement_for_user` and all the subsequent
logic expects an allocation source object, but we pass in a string.
Solution: Pass in the `allocation_source` instead of
`allocation_source.name`
> Enable enforcing hotfix

- atmosphere/settings/local.py.j2
- core/plugins.py
- cyverse_allocation/plugins/allocation_source.py
- jetstream/plugins/allocation_source.py
- scripts/add_new_accounts.py
- service/accounts/openstack_manager.py
*Problem 1*
Users reported being unable to launch instances because they had no
allocation sources. On investigation it turned that the
`AllocationSources` with their names did exist, but not the
`UserAllocationSources` which were used to link their `AtmosphereUser`
accounts to the allocation sources.
We also found that the `user_allocation_source_created` events which
should trigger the creation of the `UserAllocationSources` did exist.
The process for creating a `UserAllocationSource` relies on an
`AtmosphereUser` already existing, and happens as part of creating an
identity on a provider - in the
`service.accounts.openstack_manager.AccountDriver#create_account`.
Normally this happens when the user logs in and we know that the
`AtmosphereUser` exists.
We found another another place …
> Problem: Missing UserAllocationSources (and more!)

- .travis.yml
The `./travis/check_properly_generated_requirements.sh` was failing in the clank build. pip-compile could not work with the existing really old setuptools. So an upgrade to setuptools fixed the clank build. Additionally I added caching for pip in travis, which sped up installs from ~4min to about ~1min of pip installs.
> Fix requirements workflow

- api/v1/urls.py
- atmosphere/settings/local.py.j2
- service/quota.py
When the same account is being used by many people the UI polls the
API too frequently, causing problems for the server.
Solution: Temporarily add a short-lived cache to the most heavily used
endpoint.
> Problem: Too many requests from UI in workshops

- extras/nginx/site.conf.j2
Include nginx snippet to block calls with an invalid host header.
> Bugfix: invalid HTTP Host header causes 500

- core/hooks/allocation_source.py
Solution: When we reset `compute_used` on `AllocationSourceSnapshot` we
also reset the corresponding `UserAllocationSnapshot` objects.
> Problem: User allocation snapshots not resetting

- atmosphere/settings/__init__.py
- atmosphere/settings/local.py.j2
- cyverse_allocation/tasks.py
- features/allocation.features/alternate_story.feature
Solution: Re-use `cyverse_allocation.tasks.renew_allocation_sources`,
but simplified for a simple reset of the allocation source which does
not require the rules engine.
Next: Use the rules engine.
Note: Depends on PR #406 "User allocation snapshots not resetting" for proper functioning.
> Problem: Not resetting allocation sources

- scripts/launch_instances.py
The `scripts\launch_instances.py` file calls
`service.instance.launch_instance` - which now expects an allocation
source.
Solution: Look up the allocation source matching the username and pass
that along.
> Problem: Launch instance script fails - no allocation source

- core/models/provider.py
- core/models/quota.py
- core/views.py
- service/networking.py
Bug 1: 'admin' role users are charged for Fixed IPs they do not own
Solution: Include the project_id as part of the fixed-ip filter.
Bug 2: First account created (admin account) did not have a router_name
Solution: Let ExternalRouterTopology check if a router_name exists
and include one in a users identity,
if 'public_routers' is available.
> Fix two bugs related to user with 'admin' role

- api/v1/views/instance.py
- api/v2/views/instance.py
- service/instance.py
- service/task.py
Change logic so that 'end_date_all' happens inside the delete instance task, thereby avoiding premature end-dating of instances.
> Problem: Premature end-dating of instances on api calls to DELETE

- atmosphere/settings/local.py.j2
- cyverse_allocation/tasks.py
- features/allocation.features/alternate_story.feature
Reverting 4cb27801076b3fc8b04b6c492315e2cd8f25ec38 because it is not necessary.
```
Problem: Not resetting allocation sources
Solution: Re-use `cyverse_allocation.tasks.renew_allocation_sources`,
but simplified for a simple reset of the allocation source which does
not require the rules engine.
Next: Use the rules engine.
```
Turns out that `cyverse_allocation.tasks.update_snapshot_cyverse`
runs the rules engine which renews the allocation sources.
> Revert 'Not resetting allocation sources'

- api/v2/views/instance.py
- features/instance.features/edit_instance.feature
- features/jetstream.features/create_report_test_after_user_deleted.feature
- features/jetstream.features/special_allocation.feature
- features/steps/api_with_persona_steps.py
Anything other than changing allocation sources were explicitly omitted.
Solution: Added some logic in the `api/v2/views/instance.py` to handle 
renaming.
> Problem: Renaming instance doesn't work

- .travis.yml
Small change so that the travis check for migrations doesn't create missing migrations.
> Do not generate missing migrations

- run_tests_like_travis.sh
Solution: Add a script which roughly mirrors `.travis.yml`
Usage:
```bash
./run_tests_like_travis.sh cyverse
./run_tests_like_travis.sh jetstream
```
> Problem: Not straightforward to run tests locally like Travis

- extras/init.d/celeryd.default.dist.j2
```
OSError: [Errno 24] Too many open files
```
Solution: Set the `CELERYD_ULIMIT` variable in `celeryd.default` to a
higher number
TODO: Still not sure why this is suddenly causing a problem. Is it
something to do with the new version of Celery we're using?
> Problem: Celery sometimes reports 'Too many open files'

- service/accounts/openstack_manager.py
Solution: Add a `glance` component in the return tuple
Signed-off-by: Julian Pistorius <julian@julianpistorius.com>
~- [ ] New test(s) included to reproduce the bug/verify the feature~
~- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~
~- [ ] If necessary, include a snippet in CHANGELOG.md~
~- [ ] New variables supported in Clank~
~- [ ] New variables committed to secrets repos~
> Problem: `rtwo` return includes `glance` now

- extras/nginx/locations/atmo.conf.j2
With the adoption of Atmosphere growing, it is best to have _"no"_ or generic error/not-found/404 pages. There should be enough "styling" that the web server does not appear to be correctly configured. However, allowing for a favicon complicates the theming efforts,
overall. Here we offer "less" to gain the ability to focus on more.
See also [ATMO-1536](https://pods.iplantcollaborative.org/jira/browse/ATMO-1536)
- ~[ ] Documentation created/updated at [Example link to documentation]~(https://example.test/doc#new_section) to give context to the feature
> Problem: Error & Not Found pages have branded favicon

- extras/nginx/locations/atmo.conf.j2
The web server for `atmo` still defines a location for `/shell`. This dates back to the Airport/cloudfront era of user interface. The web shell is hosted within Troposphere now.
No _external_ ticket available for reference.
> Problem: unused Nginx location present in atmo.conf.j2

- features/jetstream.features/login_tas_api_failover.feature
- features/steps/api_with_persona_steps.py
- features/steps/tas_api_steps.py
- jetstream/allocation.py
- jetstream/exceptions.py
- jetstream/plugins/auth/validation.py
- jetstream/tests/tas_api_mock_utils.py
Solution: Modified the `XsedeProjectRequired` validation plugin to have
a fallback strategy when the TAS API is unavailable.
The strategy is to check whether the user has existing allocation
sources in the database.
In order to achieve this I had to make a clear distinction between:
1. TAS API is unavailable or throwing bad errors
2. TAS API is available, and:
a. There really is no TACC account for an XSEDE username
b. We try to find allocations or projects for an invalid TACC account
We were conflating all of these before.
This means that existing Jetstream users can log in and use Atmosphere
as long as:
- They have logged in before
- They were valid the last time we were able to check with the TAS API
Note: New Jetstream users who have never logged into Atmosphere will be
disabled until …
> Problem: Can't use Jetstream when TAS API is unreachable

- api/v2/views/web_token.py
This PR adds parameters for SFTP connections. I modified [guacamole-auth-hmac](https://github.com/calvinmclean/guacamole-auth-hmac) to use public/private keys for SSH. This also allows us to use the keys in VNC connections to enable drag/drop SFTP! These changes will rely on changes to atmosphere-ansible and atmosphere secret repos. The changes to atmosphere-ansible will use the `gateone-gen-sshkey` role to create SSH keys on Guacamole server as well since the Guacamole server looks for keys locally so they are not sent in web requests.
~~- [ ] If necessary, include a snippet in CHANGELOG.md~~
~~- [ ] New variables supported in Clank~~
> Enable sftp for all Guacamole connection protocols

- api/tests/factories/__init__.py
- api/tests/factories/instance_history_factory.py
- api/tests/factories/provider_factory.py
- api/tests/factories/size_factory.py
- api/tests/v2/test_instance_actions.py
- api/tests/v2/test_instances.py
- core/admin.py
- core/models/instance.py
- features/jetstream.features/enforcing.feature
- features/steps/api_with_persona_steps.py
- service/deploy.py
- service/instance.py
- service/mock.py
- service/tasks/driver.py
Instance does not keep track of user-initiated redeploy, reboot, and hard reboot via instance actions.
Ensure that a new `Instance Status History` entry is created for each of the three previously mentioned states.
> [ATMO-1916] Track redeploy and reboot in InstanceStatusHistory

- api/tests/factories/provider_machine_factory.py
- api/tests/factories/tag_factory.py
- api/tests/factories/version_factory.py
- api/tests/v2/base.py
- api/tests/v2/test_allocation_sources.py
- api/tests/v2/test_identities.py
- api/tests/v2/test_image_metrics.py
- api/tests/v2/test_images.py
- api/tests/v2/test_instances.py
- api/tests/v2/test_platform_types.py
- api/tests/v2/test_projects.py
- api/tests/v2/test_provider_types.py
- api/tests/v2/test_sizes.py
- api/tests/v2/test_tags.py
- api/tests/v2/test_users.py
There is a subset of tests that should be included in all /v2 API endpoint testing. One example is ensuring that `<key>` in  `/v2/<type_of_resources>/<key>` is invalid, null, or improper type that the application does not "crash" with a 500 error.
This PR can and should be improved prior to merge.
> Sanity test cases for the v2 API

- atmosphere/settings/__init__.py
- atmosphere/settings/local.py.j2
- variables.ini.dist
Django-debug-toolbar can be useful for profiling your API calls.
This configuration will enable django-debug-toolbar for your requests.
> New configuration option: Django debug toolbar (2)

- features/instance.features/edit_instance.feature
- features/steps/api_with_persona_steps.py
`edit_instance.feature` was using a step to create an identity in a way
that would only work when using the correct setup for Jetstream & TAS
Solution:
1. Use the correct step,
2. Document it in the step,
3. Add an `assert` to catch it in the future, and
4. Skip all these scenarios if running in Jetstream distribution
> Problem: Failing tests

- scripts/application_to_provider.py
Glance v1 client throws exception on line breaks in any of the metadata fields. We're likely to have line breaks in `application_description` for many images. This PR replaces line breaks with ` -- `.
> Stripping line breaks from application_description when talking to Glance API V1 Client

- core/models/identity.py
- scripts/application_to_provider.py
Each call to `api/v1/profile` was computing a users allocation across all their instances (old style allocation), and was ignoring the result 😆 . There is a lot of dead code to nuke.
> Don't compute unnecessary and very expensive query

- api/v1/views/token.py
- api/v2/views/emulate.py
- features/steps/allocation_story_steps.py
The recent refactor of `get_or_create_token` in `django_cyverse_auth`
changed from using a username to using `AtmosphereUser` objects.
This was not updated in the `emulate` view.
Solution: Change remaining occurrences of `username` to `user` when
calling `get_or_create_token`
~- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~
~- [ ] If necessary, include a snippet in CHANGELOG.md~
~- [ ] New variables supported in Clank~
~- [ ] New variables committed to secrets repos~
> Problem: Emulate endpoint broken

- HACKING.md
- README.md
- api/v2/serializers/details/resource_request.py
- api/v2/serializers/fields/identity.py
- api/v2/serializers/fields/status_type.py
- api/v2/serializers/fields/user.py
- api/v2/views/resource_request.py
- core/models/identity.py
**Problem:**
API call to resource requests is too slow
**Solution:**
Prefetch data in the nested serializers, create less objects
See [documentation](https://github.com/cyverse/atmosphere/pull/447/files#diff-88333ba11114e014e87198d04680144d).
The API endpoint for 400 models went from making 3000 db queries to about 10 and from roughly 20s total request time to 1s. Many of our apis will experience similar speedups from these fixes. 
Even though the queries were improved by a factor of 300, the time was only improved by a factor of 20, so database optimization isn't everything—serialization is also costly.
> Optimize resource request serialization

- api/v1/views/token.py
While fixing the emulate endpoint in PR #464, I broke it in a different
way. I didn't fully understand how the emulate process worked. I assumed
the `username` and the `user` were interchangeable based on the other
examples of `get_or_create_token`. But in this case the `username`
corresponded to a different user (the user to emulate), and not to the
logged-in user. As a consequence the user ended up emulating themselves.
Solution: Look up the user to emulate and pass that into the
`get_or_create_token` function.
- ~[ ] New …
> Problem: Emulate is broken

- api/v2/serializers/summaries/size.py
The solution offered here is included `'root'` in the summary serializer for Size.
Size has the distinction between a "root" and ephemeral storage disks associated with a _flavor_. This meant that `"disk"` for Sizes in Atmosphere were being set to `0` and this would mean they're excluded from being displayed in the user interface, Troposphere. 
Unfortunately, the Instance Details will not show anything for storage as the "size" data associated with an Instance has this omission. 
<details>
For `GET /api/v2/instances/4101ce77-352b-44fe-a8eb-701479c42700`, you see the `"root"` attribute is *not* included in `"size"`:
```
{
"id": 34581,
"uuid": "4101ce77-352b-44fe-a8eb-701479c42700",
"url": "https://atmo.cyverse.org/api/v2/instances/4101ce77-352b-44fe-a8eb-701479c42700",
"name": "Ubuntu …
```
> Problem: SizeSerializer does not "root" disk storage attribute

- api/v2/views/web_token.py
Fix for merged PR #424 
The line with `request_string += "guac.color-scheme=white-black"` is missing a "&"
This didn't cause any failures, but prevented Guacamole from parsing the additional parameters. This PR simply adds a "&" in front of that string.
> Fix for PR #424 - Guacamole key auth and default Guac shell color

- api/v2/serializers/details/project_volume.py
- features/steps/api_with_persona_steps.py
- features/volume.features/create_and_edit_volume.feature
- service/mock.py
Problem: Creating volume (for project) fails
URL: `/api/v2/project_volumes`
Error:
```
django.db.models.fields.related_descriptors:RelatedObjectDoesNotExist: Volume has no instance_source.
```
Background: The refactoring of the project-volumes relationship meant
that the many-to-many table doesn't exist anymore. The way the new code
was structured meant that a new volume was created, instead of setting
the `project` attribute on an existing volume.
We only caught it because the volume blew up due to a missing 
attribute - `instance_source`.
Solution: Added an explicit `create` method on `ProjectVolumeSerializer`
which sets the `project` attribute on the volume
This overrides the default creation behavior which only made sense in
the prior arrangement.
- ~[ ] Documentation created/updated …
> Problem: Creating volume (for project) fails

- service/instance.py
Problem:
api was trying to render an AsyncResult into a template, which is not serializable
Solution:
revert to prior functionality which returned None, which is serializable
> Revert to previous return None, which is serializable

- core/migrations/0092_set_unknown_size_instance_status_history.py
`Size` is not in scope where it is referenced.
Solution: Move its instantiation into the `get_unknown_for_provider`
function where it is used.
@steve-gregory Could you please check this?
> Problem: Migration potentially broken

- api/v1/views/instance.py
- api/v2/serializers/details/image_version.py
- api/v2/views/project_volume.py
- api/v2/views/provider_machine.py
- core/models/group.py
- core/models/provider.py
- core/query.py
- service/driver.py
- service/exceptions.py
- service/instance.py
- service/task.py
End-dated providers are not visible within the GUI/API (Archived)
To include end-dated providers in API responses use '?archived=True'
End-dated providers will throw ProviderNotActive exception.
Inactive providers are visible with the GUI/API
Inactive providers _are not available for instance launch_ within the GUI/API
Inactive providers can still have drivers created.
> Differentiate between inactive/end-dated

- core/email.py
**Problems:**
1. emails have no newlines
2. rt links to the wrong url to address the request
**Solutions:**
1. don't send emails as html, when they are actually plaintext
2. link to the proper url supplied by atmosphere
> v27 fix admin emails

- service/tasks/driver.py
Partial fix #491
Solution: Import it. :)
TODO: Figure out where `_parse_steps_output` went and reproduce
functionality
> Problem: `LibcloudDeploymentError` not imported in tasks/driver

- core/models/application.py
- service/machine.py
- service/tasks/monitoring.py
This work ensures that we mark private images as "shared" (=> you + admin).
With changes made to handle group ownership, images that were "private" are considered "shared"; the explanation is that they're shared with a user (you) and the admin - always. So a private or shared with specific user image are both treated as "shared" within the glance catalog (I
think).
This is noted and captured here as a fix for issue related to imaging encountered during a verification of "private" images, and this updated semantic is required.
> Ensure visibility handled consistently for images

- cyverse_allocation/tasks.py
- scripts/force_renew_allocation_sources.py
Solution: Tweak existing functions to allow overriding `compute_allowed`
and add a script which calls `renew_allocation_sources` for all
allocation sources with `default` strategy.
> Problem: Want to reset renewal date for allocation sources

- extras/uwsgi/atmo.uwsgi.ini.j2
Thousands of them. Very noisy.
See https://github.com/getsentry/raven-python/issues/732
Solution: Add some exclusions to `atmo.uwsgi.ini` template as
recommended by GitHub issue above.
> Problem: Spurious 'IOError' in Sentry

- .travis.yml
Our travis build should test the production setup. Prior it was only testing the development packages, because it needed those to run tests. Now we run manage.py check with the production environment, this should help us catch import errors and other mistakes given our production packages.
> Test imports in production environment

- core/models/allocation_source.py
- features/jetstream.features/special_allocation.feature
- features/steps/allocation_steps.py
- features/steps/api_with_persona_steps.py
Solution: Return -1 from `AllocationSource.time_remaining` when a user
is passed in, but no allocation snapshot is found.
Fixes #454, PR #501 rebased for `v27`
> Problem: Missing snapshot will break monitor_allocation_sources

- core/management/commands/maintenance.py
This provide a Django command for starting and stopping maintenance. 
The `start` operation of the `maintenance` command will ask for overrides to sensible defaults. These are used when creating an instance of a `MaintenanceRecord`. 
The `stop` operation of the `maintenance` command will _"end-date"_  any active `MaintenanceRecord`s, with the current time (provided by `django.utils.timezone.now()`).
This is an initial version that is not :100:% robust; yet, covers most of the common situations when operating planned maintenances. 
A "source" _included_ version of this is slated for a pull request against Troposphere that would provide the **exact** same commons. This would avoid having to know the namespaces of various models when performing maintenance.
If accepted, this would warrant …
> Provide convenience for starting/stopping maintenance

- service/monitoring.py
Solution: Added parameter back which recently went missing.
This is a hotfix version of this PR: https://github.com/cyverse/atmosphere/pull/510
> Problem: Missing `user` param

- .gitignore
- .travis.yml
- run_tests_like_travis.sh
We really just want to see the failing scenarios.
Solution:
- Use the `rerun` output format
- Output to a file instead of `stdout`
- Add line to run failed scenarios in the new file (if any)
> Problem: `behave` is very verbose

- core/admin.py
`AttributeError: 'ApplicationVersionMembership' object has no attribute 'application_version'`
Solution: Use `image_version` instead of `application_version`
> Problem: `AttributeError` on `applicationversion` admin

- atmosphere/celery_router.py
- dev_requirements.txt
- requirements.txt
- service/deploy.py
- service/instance.py
- service/task.py
- service/tasks/driver.py
- service/tasks/machine.py
- service/tasks/volume.py
Solution: Remove libcloud deployments & replace missing scripts with ansible roles/playbooks.
- Imaging tasks to sync/freeze in playbooks/imaging
- Volume mount/unmount tasks in playbooks/instance_actions
- Update `service` to remove all references to ScriptDeploy and
LibcloudDeployments
- Use new functionality in subspace>=0.5.0 to inspect the 'register' variable
inside of ansible. Provide hints for how `lsof` and `unmount` failures can be
recorded for a future PR that deals with "improvements to volume status history" (link coming soon)
> Problem: Legacy libcloud deployments mixed in with ansible

- api/tests/v2/test_allocation_sources.py
- api/v2/serializers/post/token_update.py
- atmosphere/plugins/accounts/creation.py
- atmosphere/settings/local.py.j2
- core/models/allocation_source.py
- cyverse_allocation/plugins/allocation_source.py
- cyverse_allocation/tasks.py
- features/instance.features/edit_instance.feature
- features/jetstream.features/enforcing.feature
- features/jetstream.features/monitor_jetstream_allocation_sources.feature
- features/jetstream.features/special_allocation.feature
- features/steps/tas_api_steps.py
- features/volume.features/create_and_edit_volume.feature
- service/instance.py
- variables.ini.dist
- Update the AccountCreationPlugin topology to better explain which plugin to use, and why.
- Continue with a simple approach that uses `/token_update` to do all of the heavy lifting
- Create a new 'AccountCreationPlugin' (DirectLogin) and include the ability to auto-create a new projects for the user  as part of the plugins settings.
- New settings available: `ALLOCATION_SOURCE_COMPUTE_ALLOWED`, `AUTO_CREATE_NEW_PROJECTS`
> Problem: OpenstackLoginBackend fails after new account creation logic

- service/instance.py
- service/task.py
- service/tasks/driver.py
- Given multiple ports, select a port which is ACTIVE and attached
- Fix provided in the 'ready_to_deploy' task, so that it can be caught
and fixed with a simple redeploy.
- Rename task: 'add_floating_ip'->'initialize_instance_networking'
Rationale:
- This task is doing a _whole lot_ more than just adding a floating IP
- Goal of the task: instance is ready to network by the end of the task.
- Set metadata to 'initializing' for a redeploy/reboot
Rationale:
-  avoid 'bouncing back' to error states
> Problem: Race condition can create two fixed IPs, causing networking errors

- extras/uwsgi/atmo.uwsgi.ini.j2
Solution: Use `LOCAL_DEV: True` variable to enable uWSGI
`python-autoreload` feature.
> Problem: Manual uWSGI reload in dev environment - Nope

- service/deploy.py
Problem: Top level import of subspace.runner creates race condition
Solution: Move calls into tasks that need subspace 
service/deploy.py gets evaluated by celery workers running as root or www-data. The import of subspace results in some side effects, ansible goes and creates directories (with the perms of the current user).
So if celery's imaging worker which runs as root imports ansible, then those
directories will have root permissions, breaking ansible for www-data (i.e.
the other celery workers).
> Avoid global subspace import

- core/models/application.py
- core/query.py
- when using 'id in' queries, use a list() over a QuerySet.
- *Most important* Rather than join membership tables, do a lookup on individual tables, and look for results in query.
- Use prefetch_related/select_related on API get_queryset call
> Optimize SQL queries to avoid slow /v2/images calls.

- service/accounts/openstack_manager.py
Before atmosphere runs subspace, it checks that ssh deploy key is the key that
was injected into the instance. The check was failing because of a trailing
new line. Same key is used to inject as is to perform the check, just reading
from python didn't strip the newline.## Checklist before merging Pull Requests
> Fix trivial key mismatch

- service/accounts/openstack_manager.py
- service/machine.py
- service/tasks/monitoring.py
Problem: Edge-case causes ALL atmosphere users to be added as members to an Application.
Solution:
- Fix the edge-case, only return valid projects.
- Create a method for 'cleaning up' already-affected Applications on the production servers
> WIP: Edge-case causes problems in monitor_machines

- core/fixtures/boot_script.json
> Problem: ScriptType missing on new databases

- service/deploy.py
> Problem: AnsibleDeployError does not include enough information for triage

- core/models/application.py
- core/models/application_version.py
- core/models/machine.py
- core/tests/application.py
- core/tests/helpers.py
- service/accounts/openstack_manager.py
- service/tasks/monitoring.py
Problem(s):
- (1) Application with empty access-list returned _all users_ which made private images "Shared with >128 Users" error show up
- (2) New applications are being created with 'v. VersionName' in the
- (3) New applications are being created for each version update.
Solution(s):
- (1) return AtmosphereUser.objects.none() when access_list is empty.
- (2) Imaging will include version name, and monitoring should strip
version name before processing.
(This was noted in comment but never implemented)
- (3) Rely on application_uuid metadata and "fall back" on the
glance image name to be the secondary 'key' of truth.
If API users are creating images with the _same name_ and _same
application UUID_ then we will need to find a new way
to address this problem.
Cleanup related to the …
> Problem: machine monitoring creates errors in image catalog

- core/metrics/application.py
When an image has not be launched, we hit `total_launched = 0` and then
the percentage calculation will throw:
```
...
>>> ZeroDivisionError: float division by zero
```
This sets the percent to `0.0` and only does the division if we have launches.
Note: when trying to test or reproduce this, you might need to do a clear of the redis cache for these calculations to be performed:
```
$ redis-cli flushall
```
One image that did *not* have launced in my local test envirionment was
- https://local.atmo.cloud/application/images/1468
> Problem: success percent might cause division by zero error

- service/deploy.py
- Allow atmosphere to pass `SSH_IDENTITY_FILE` to atmosphere-ansible as extra_vars, for both `ready_to_deploy` and `instance_deploy` playbooks.
> Problem: atmosphere-ansible ssh setup tasks can be hard to debug

- core/models/boot_script.py
- core/tests/boot_script.py
Remove special characters before sending script_text to ansible.
Provide a test case to prove that the solution works.
> Problem: ansible fails when script text includes special characters.

- core/fixtures/provider.json
Remove the default providers from fixtures. Only the `ProviderType` and `PlatformType` are necessary.
> Problem: Including providers in fixtures can cause a "bounce-back" of end-dated values

- service/instance.py
- service/monitoring.py
Create a metadata 'escape hatch' for instances with ephemeral drive mounted to /home. 
Treat these instances differently by ensuring any call to 'Shelve' will actually suspend to avoid losing data.
> Problem: Instances with ephemeral storage mounted to /home cannot be shelved

- scripts/application_to_provider.py
Glance has made API changes in version 2.5 which [add community-level image sharing](https://specs.openstack.org/openstack/glance-specs/specs/newton/approved/glance/community_visibility.html). The new image visibility sematics use `private` to mean "not shared with anyone, only accessible to owner", and `shared` to mean "private but can have additional members". We were previously using "private" when, for Glance API v2.5+, we should now use "shared". This PR fixes `application_to_provider.py` to reflect this.
> application_to_provider bugfix for Glance API v2.5 image visibility

- service/tasks/monitoring.py
Solution: Changed `glance_image` to `cloud_machine` (Seemed plausible)
> Problem: Undefined name `glance_image`

- atmosphere/plugins/machine_validation.py
- service/accounts/openstack_manager.py
- service/tasks/monitoring.py
- Legacy clouds need to call 'list images' twice and append  info to the v2 api.
- Skip machines if their status is 'queued' or 'saving'
> Fixes to monitor_machines and validation

- scripts/application_sync_providers.py
- scripts/application_to_provider.py
- Fixed: `application_to_provider` previously did not migrate custom image metadata, such as `atmo_image_include` which J7m is using as part of their machine validation strategy; this caused `InstanceSource`s in replica providers to be end-dated by `prune_machines`.
- Fixed: `application_sync_providers` previously only looked at active (non-end-dated) `InstanceSource`s + `ProviderMachine`s on a replica provider to determine if an `Application` was "complete" on that provider; this caused unnecessary work for the script when the `Application` was complete on a replica provider but at least one of its `InstanceSource`s was end-dated.
- Refactored the part of `application_to_provider` which sets metadata, for less code duplication
> Metadata syncing refactor

- api/v2/views/base.py
- api/v2/views/resource_request.py
Problem: attempt at removing RT from resource request approval was too ambitious
Solution: send resource requests to RT
We are going to continue sending resource requests to RT until the admin
resource request view is a closer replacement. Right now there's no way to
view closed requests and no way to reach out to the user for clarification.
This reverts commit f7702f309f69ae51ed8b757357c6fa86449783df.
Dependent pr https://github.com/cyverse/troposphere/pull/736
> Revert "Remove the action that sends requests to RT tracker"

- api/tests/v2/test_allocation_sources.py
- cyverse_allocation/cyverse_rules_engine_setup.py
- cyverse_allocation/tasks.py
Solution: Refactor rules parser and add a `on_calendar_day` strategy
> Problem: Allocations should renew on first day of calendar month

- api/tests/v2/test_resource_requests.py
- core/email.py
- core/templates/core/email/resource_request.html
Problem: email sent to RT during test failed
Solution: fix email logic to no longer require the submitting user to have identities
This fixes a failing test when the resource request email is sent. The admin
url is supplied and passed by troposphere. It's optional, the default url is
constructed from the user's selected identity. Because the test user has no identities, the test failed.
There is no longer any reason to try and construct this admin_url in the
template email from an identity, so it has been removed.
The tests have been updated to reflect that troposphere provides an admin_url. The email template supports an optional admin_url if it's not supplied.
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking …
> Fix old requirment that resource request is associated with identity

- api/v2/views/resource_request.py
This resolves a Travis CI build failure. It brings back a variable, `instance`, removed in #554.
Thank you Travis CI! 🎉
> Problem: unused variable became "used" again

- api/tests/v2/test_web_tokens.py
- api/v2/urls.py
Problem: The original commit rewrote the urls incorrectly
Solution: When not using a viewset, wrap with `url()`
I added a small test to ensure that the url config resolves correctly.
> Fix incorrect url definition in 036cc2e1046

- service/quota.py
Problem: 
Updating quota would often fail with the following message:
```
Quota limit must be greater than or equal to ...
```
Solution:
Send `force: True` in the body of the request
Here are the official docs
https://github.com/openstack/nova/blob/master/api-ref/source/os-quota-sets.inc#update-quotas
> Fix quota cannot exceed limit

- .travis.yml
- CHANGELOG.md
- core/plugins.py
- cyverse_allocation/plugins/allocation_source.py
- features/allocation.features/enforcing_override.feature
- features/jetstream.features/enforcing_override.feature
- features/steps/allocation_steps.py
- features/steps/api_with_persona_steps.py
- features/volume.features/create_and_edit_volume.feature
- jetstream/plugins/allocation_source.py
- requirements.in
- requirements.txt
- service/tasks/monitoring.py
- travis/check_properly_generated_requirements.sh
Problem: Need admin override for overage enforcement
Required behavior:
- Ignore enforcement/always allow: Allow allocations to "run" regardless
of SUs remaining in the allocation
- Always block: Prevent allocations or accounts (as appropriate) from
"running" regardless of SUs remaining in the allocation
Solution:
- Added a `get_enforcement_override` method on the allocation
source plugins
- The `monitor_allocation_sources` task checks the return value of this
method for every user + allocation source combination. If the value is:
- `NEVER_ENFORCE`: Enforcement is always skipped
- `ALWAYS_ENFORCE`: Enforcement is always triggered
- `NO_OVERRIDE`: Enforcement depends on the `compute_used` (default)
For the initial version of this feature both the CyVerse & Jetstream
plugins will check the …
> Enforcement override

- api/v2/views/instance.py
- api/v2/views/volume.py
- core/models/instance.py
This added the ability to filter by `provider_id` for responses from:
- api/v2/volumes
- api/v2/instances
This is a "feature-enabling", enhancement request for the development of the user interface. 
See [ATMO-2132](https://pods.iplantcollaborative.org/jira/browse/ATMO-2132).
> Problem: cannot filter v2 Volumes & Instances by provider_id

- features/allocation.features/story.feature
Problem: spurious broken test
Solution: explicitly include a current time in the test
This test fails today, i'm guessing because of how renewal occurs. None the less, the test shouldn't be a function of when it is run.
> Fix test breaking because of implicit dependency on current time

- api/tests/v2/test_instance_actions.py
- features/allocation.features/enforcing_override.feature
- features/jetstream.features/enforcing_override.feature
- features/steps/allocation_steps.py
- service/instance.py
Based on previous work: https://github.com/cyverse/atmosphere/pull/565
- Allow instances to always be started/resumed/unshelved if they are
associated with an allocation source which is set to `NEVER_ENFORCE`
- Prevent instances from being started/resumed/unshelved if they are
associated with an allocation source which is set to `ALWAYS_ENFORCE`
Solution:
- Run `check_allocation` in `service.instance.run_instance_action` if
the action is in `('start', 'resume', 'unshelve')`
- ~[ ] If creating/modifying DB models which will contain secrets or sensitive information, PR to [clank](https://github.com/cyverse/clank) updating sanitation queries in …
> Problem: Use enforcement override for instance actions

- service/instance.py
When an instance is started, a call is made to check_allocation with an allocation source snapshot. However, check_allocation expects an allocation_source. This causes an assertion error to be thrown, which results in a generic service error.
Here is a stack trace, which would lead to the assertion error. The error is introduced in the third trace at line 2053.
```
/opt/dev/atmosphere/api/v2/views/instance.py(99)actions()
98             return self.list_instance_actions(request, pk=pk)
---> 99         return self.post_instance_action(request, pk=pk)
100
/opt/dev/atmosphere/api/v2/views/instance.py(119)post_instance_action()
118         try:
--> 119             result_obj = run_instance_action(user, identity, instance_id, action, action_params)
120             api_response = { …
```
> Fix invalid argument to check_allocation

- api/tests/v2/test_instance_actions.py
- core/hooks/allocation_source.py
- features/steps/allocation_steps.py
- service/instance.py
Problem: Testing allocation logic requires setting ENFORCING=true, which is dangerous
Solution: Remove ENFORCING from the equation
~~- [ ] New test(s) included to reproduce the bug/verify the feature~~
~~- [ ] Documentation created/updated at [Example link to documentation (https://example.test/doc#new_section) to give context to the feature~~
~~- [ ] If creating/modifying DB models which will contain secrets or sensitive information, PR to [clank](https://github.com/cyverse/clank) updating sanitation queries in `roles/sanitary-sql-access/templates/sanitize-dump.sh.j2`~~
~~- [ ] If necessary, include a snippet in CHANGELOG.md~~
~~- [ ] New variables supported in Clank~~
~~- [ ] New variables committed to secrets repos~~
> Remove unnecessary enforcing restrictions

- api/tests/v2/test_instance_actions.py
- api/v1/views/instance.py
- api/v2/views/instance.py
- service/exceptions.py
- service/instance.py
**Dependenices:**
Problem: when allocation name is blacklisted, user gets cryptic error when launching
Solution: Give them a precise error
This is sort of an edge case but warranted. Troposphere no longer performs allocation validation before launching, it defers to the backend to raise exceptions and thus trusts the backend to have good errors.
~~- [ ] If creating/modifying DB models which will contain secrets or sensitive information, PR to [clank](https://github.com/cyverse/clank) updating sanitation queries in `roles/sanitary-sql-access/templates/sanitize-dump.sh.j2`~~
~~- [ ] Reviewed and approved by at least one other contributor.~~
~~- [ ] …
> Raise separate error for blacklisted allocations

- api/v2/views/web_token.py
Previous versions of Guacamole required that the authentication plugin removed the first two characters of the connection ID in order to add some sort of extra metadata the the ID. This was removed, so the auth plugin no longer removes the two characters, so neither should Atmosphere.
**Before this goes into production**, please coordinate with me to make sure Guacamole server has the same changes because they have to go at the same time.
> Guacamole web shell and desktop link generation update

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
Proposed a changelog process (see https://github.com/cyverse/troposphere/pull/766). The idea is that each pr contributes to the changelog so that come time for a release the work is done.
One notable difference from the last changelog is that each release needs to represent an exact version. Before we had the notion of a milestone, like v30. Instead we'll now just have each release as a tag. v30-0, v30-1, v30-2, etc, each with its own section in the changelog.
- https://github.com/cdosborn/atmosphere/blob/3d51b04a69618dd3f95de339ecc832247af75749/CHANGELOG.md
> Propose a documented changelog format and changelog contribution process

- CHANGELOG.md
- core/management/commands/maintenance.py
- core/management/commands/test_maintenance.py
Change ./manage.py maintenance sub-command to be easier to test and add features
I was making changes to `atmosphere.version.git_branch`, and found that this command would be affected. I wanted to write some tests to ensure that the command would still work. However, the previous command would not allow you to pass some arguments and not others. If you omitted any, it would go into an interactive mode. I couldn't test whether the defaults were working, because of this mode. The command has been pretty useful during deployments, so these changes just make the tool  more command-line friendly.
- Defaults are used if not overriden
- Interactive mode is removed and replaced with --dry-run
- The start_date format accepts timezones now.
- The --start-now flag was removed, this is the default if …
> Change maintenance command to be non-interactive

- service/instance.py
- service/tasks/driver.py
On unshelve instances would sometimes fail to get a fixed ip
Rather than update ip on current port, delete all ports and create a new one
I changed the name of add_fixed_ip, because we are taking a quite different approach here. We delete all an instance's ports, and then instruct nova to attach the instance to a subnet. Nova takes care of creating a port.
This fixes an outstanding issue in nova[0]. Prior to this change we kept ports around and then removed/added fixed ips. However, when an instance and its port are created, they each have an availability zone(AZ), when we unshelve an instance its AZ may change. If it does change, openstack fails to update the device owner AZ of the port and attaching a fixed ip fails because no ports exist in the AZ. …
> Fix unshelved instance failing to get fixed ip

- CHANGELOG.md
- service/instance.py
- service/tasks/driver.py
This pr https://github.com/cyverse/atmosphere/pull/599 was brought into v31, and thus v31 needs to now be brought into master
> Bring in the latest from v31

- CHANGELOG.md
- api/base/views/__init__.py
- api/base/views/version.py
- api/tests/base/test_version.py
- api/tests/test_pattern_matches_viewset.py
- api/tests/v1/test_version.py
- api/tests/v2/test_version.py
- atmosphere/version.py
- core/management/commands/maintenance.py
- core/tests/test_version.py
Problem: api/v{1,2}/deploy_version is not returning git information from atmosphere-ansible
Solution: return information about atmosphere-ansible like we return it from atmosphere
There was a decent amount of refactoring, and a decent amount of tests added!
> Fix broken atmosphere ansible version reported from api

- CHANGELOG.md
- service/instance.py
- service/tasks/driver.py
Try different approach to working around openstack port availability zone issue
After upgrading Marana to Pike we found that ports which were attached post boot, would never successfully attach. This meant that every time an instance would boot (start/unshelve) minus initial launch, it would not be reachable. A workaround was discovered to enable allow-hotplug for the given interface in cloud-init, but it was deemed more complicated than simply preserving the ports.
We were deleting/recreating the ports in the first place, because of a bug which affected j7m https://bugs.launchpad.net/nova/+bug/1759924.
Rather than add/delete ports, add/remove fixed ips, but explicitly check if we're dealing with the availability zone issue and then try deleting/recreating the port. It is unknown why j7m …
> Make another attempt to fix adding fixed ips

- CHANGELOG.md
- service/quota.py
Fix quota update causing index out of range
Updating a users quota, would trigger an index out of range error
Use a different api for fetching the users tenant id
In the act of changing quota, we require a tenant id for the user. The original api which fetched this id, did so through a side effect of establishing a connection to the nova compute api. This side effect changed when marana was upgraded to use the 2.1 compute api rather than the 2 version. It changed as a result of a new url returned from the service catalog discovery.
We are no longer using this method in rtwo `_get_tenant_id`.
I tested against marana, workshop, iu, and tacc.
> Fix quota update bug "index out of range"

- CHANGELOG.md
- service/quota.py
Updating a user's volume quota, would return a successful response including the updated quota values. However, the values wouldn't actually be updated in openstack.
Pass a tenant id rather than a tenant name in /os-quota-sets/<tenant id>
The current OS api[1] silently fails, reporting a successful update, even when the update did not occur. Tested against all providers in use. Verified that storage is updated from OS pov.
[1] https://developer.openstack.org/api-ref/block-storage/v3/index.html#quota-sets-extension-os-quota-sets
> Fix volume quota update

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
Upgrade to rtwo 0.5.19
This resolves the change in rtwo that caused every attempt of a user to fetch their instances, to try and fetch all_tenants instances, which is forbidden by default on most clouds.
This change was hotfixed during the j7m release.
> Upgrade to rtwo 0.5.19

- CHANGELOG.md
- scripts/application_to_provider.py
Glance Client v1 uses a different method for uploading image data; this PR accommodates that.
This codepath was previously untested with Glance Client v1 because we were using the "direct iRODS transfer" mode of application_to_provider. We recently stopped using that (because Marana Cloud Glance is now backed by Ceph), and this bug surfaced.
Also, apparently in Glance API v1, it is valid for an image's checksum to be missing even though that image is in active state; we can catch this and log a warning.
> Fixes for application_to_provider Glance client v1 native (non-iRODS) upload method

- CHANGELOG.md
- api/v2/views/email.py
- core/templates/core/email/feedback.html
Please describe your pull request. If you're solving a problem, include a oneline problem and oneline solution statement. Otherwise, just begin with a single line summary.
> Remove confusing Provider label in feedback email

- CHANGELOG.md
- service/tasks/monitoring.py
AttributeError: 'NoneType' object has no attribute 'get_image_members'
Remove irrelevant code
During monitor_machines_for we fetch the latest images from the cloud and sync those with our database. Part of that syncing is creating the Membership relations which affect who can see an atmosphere image (more correctly a provider machine). There was a bug in this process.
For each image we convert to a provider machine, we check if a machine request exists on any provider. If one does exist and the provider of the request doesn't equal the provider of the machine we're syncing, then we copy the image members of that original provider onto this provider machine. The error is that we never check if that original provider is active (i.e still running). If it's not active, then we cannot fetch …
> Fix monitor_machines_for in the presence of inactive clouds

- CHANGELOG.md
- atmosphere/celery_router.py
- atmosphere/settings/__init__.py
- core/models/instance.py
- service/instance.py
- service/tasks/driver.py
This PR removes the code that removes private network resources from inactive (suspended/stopped/shelved instances). This effectively leaves the private subnet and fixed IP intact. We are still removing floating (public) IP addresses.
Currently, Atmosphere(2) removes fixed IP addresses (and possibly private networks) from instances when they are stopped, suspended, or shelved, and also periodically on all 'inactive' instances. This was originally done for at least the following reasons:
> * support for isolated tenant subnets, where each tenant gets their own subnet of /24 (though in hindsight /24 is probably too large)
> * at the time, neutron overlapping ips didn't work for us as expected or there was some gotcha, which I forget
> * because we assumed that subnet space would be finite …
> Preserve private networks and private/fixed IPs for inactive instances

- CHANGELOG.md
- atmosphere/settings/__init__.py
This task is taking >1 hour to run in production for each provider, doesn't make sense to run every 30 mins. Image import via this method is rare, and `monitor_machines` can always be run on-demand if needed. See #atmosphere_issues channel in Jetstream Slack from morning of 2018-06-15.
> Run monitor_machines once each night rather than every 30 mins

- CHANGELOG.md
- jetstream/test_tas_api.py
Fix test failures when run consecutively
Running tests twice causes failures
Remove the memoize cache before test runs
This would fail if run twice:
```
./manage.py test --keepdb jetstream.test_tas_api.TestJetstream.test_validate_account
```
It would fail because the cassettes did not reflect the correct number of plays, i.e. api calls didn't happen like we expected. Normally cassettes store the results of a first http call, and intercept and respond to all future calls with the results of the first. We assert that the cassette was called a certain number of times. However, django-memoize intercepts the functions that would even make these http calls, so the cassettes were under-reporting the number of playbacks.
> Django tests fail when run consecutively

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
- service/tasks/driver.py
Problem: When creating a floating IP address and associating it to an instance, rtwo chooses an arbitrary external network (the first one that happens to be returned from the API). If there are multiple extrenal networks, rtwo may select a network which is unreachable from the user's private network (no router connects them).
Solution: When using external router topology, determine the correct external network (based on the user's assigned public router) and explicitly specity it when creating a floating IP address.
Co-depends on [rtwo #27](https://github.com/cyverse/rtwo/pull/27)
> If using External Router topology then determine external network ID when adding floating IP and explicitly pass it to rtwo

- CHANGELOG.md
- dev_requirements.txt
- extras/logrotate.atmosphere
- requirements.in
- requirements.txt
- service/deploy.py
- service/tasks/driver.py
- service/tasks/volume.py
Replace Subspace by using Ansible's PlaybookCLI to deploy instances.
The main purpose of this PR was to reduce the amount of core Ansible code that had to be modified by Subspace in order to make it easier to update the program to work with newer Ansible versions. In the end, Subspace was completely removed.
In the place of Subspace, we use Ansible's PlaybookCLI object. The `execute_playbooks()` function adds two attributes to `ansible.constants` (`ansible.cfg` values) to suppress Ansible playbook stdout and set the directory used for logging. This is done here because `ansible.cfg` expects a file path, not a directory path, and would cause errors on regular runs of `ansible-playbook` and we do not want to suppress stdout on regular `ansible-playbook` runs. Then, it loops through playbook …
> ATMO-2149: Atmosphere deploy without Subspace

- service/tasks/driver.py
Fix wrong object reference
Identity is an rtwo instance not a core.models instance
Refer to the correct variable
> Fix wrong object reference

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
- service/deploy.py
This PR upgrades the Ansible version used by Atmosphere to the latest (2.6.1). The only change required was the `--inventory-file` argument was changed to just `--inventory`.
Related PR: Atmosphere-Ansible [PR #155](https://github.com/cyverse/atmosphere-ansible/pull/155)
> Upgrade Ansible version to the latest (2.6.1)

- CHANGELOG.md
- api/v1/views/instance_query.py
- api/v2/views/machine_request.py
- atmosphere/celery_init.py
- atmosphere/settings/__init__.py
- core/email.py
- core/models/application.py
- core/models/instance.py
- core/tasks.py
- core/views.py
- scripts/add_new_provider.py
- scripts/admin_update_keypairs.py
- service/accounts/eucalyptus.py
- service/accounts/openstack_manager.py
- service/deploy.py
- service/exceptions.py
- service/instance.py
- service/networking.py
The proper way to import settings is via 'from django.conf import settings'. This is because settings are a part of Django's abstractions. For example, `@override_settings` has no effect unless settings are imported this way.
https://docs.djangoproject.com/en/1.10/topics/settings/#using-settings-in-python-code
> Prefer importing settings from django.conf

- CHANGELOG.md
- api/v2/views/instance.py
When detaching a volume, run_instance_action would return the volume. The api would then attempt to return that volume object, rather than a serialized volume. The action api doesn't need to return anything besides the status of the action. It should definitely not know how serialize objects like instances and volumes.
> Simplify v2 action api, fix volume detach 500

- core/tests/helpers.py
This pr fixes an issue introduced in the build.
I merged two prs back to back that each individually passed the build, but resulted in a build failure together. I didn't completely remove all references to Allocation, there were some references in our old tests which were not being run. I merged the pr to re-incorporate these old tests after the pr which removed allocation. The result is that these tests had a reference to the old allocation system, which then prompted a failure since the old allocation had been removed.
> Remove reference to non-existent Allocation model

- CHANGELOG.md
- scripts/application_to_provider.py
Apparently newer Glance client packages don't even have a v1 attribute, in which case 1. this code throws an `AttributeError` and 2. We're definitely not using old Glance v1. So, don't even test to see if we have a Glance v1 client. This is already hotfixed on J7m prod.
> For application_to_provider, determine correct upload method based on Glance client version specified in main function

- .travis.yml
- CHANGELOG.md
- api/tests/v2/test_instance_actions.py
- api/tests/v2/test_instances.py
- api/v1/views/instance.py
- service/allocation_logic.py
- service/exceptions.py
- service/instance.py
- service/licensing.py
- service/monitoring.py
- service/search.py
- service/tasks/__init__.py
- service/tasks/driver.py
- service/tasks/machine.py
- service/tasks/monitoring.py
- service/tasks/volume.py
- service/volume.py
Increase linter from "low" to "medium"
Each commit fixes a single lint violation. I don't expect a reviewer to look at each commit. There are only a handful of commits that change more than one line, and they all fell into the same category of issue relating to imports. 
File A, would `from foo import X`, but A would never use X at all. So the linter would suggest to remove that import. However file B, would import `X from A`. So file B would have to be updated to also import from `foo`. A file should import a value from the package where the value is defined.
> Make linter significantly more strict

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
Upgrade to django-cyverse-auth 1.1.6
A few other dependencies were changed as well but it was all done with `pip-compile` so I assume it is fine.
> Upgrade django-cyverse-auth to 1.1.6 from 1.1.4

- CHANGELOG.md
- service/accounts/openstack_manager.py
There was a lingering reference to a deleted model through
Remove the reference
The provider's config includes the dnsnameservers. Its use here is a relic.
> Fix reference to deleted model

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
In django-cyverse-auth 1.1.6, there was usage of an undefined value breaking OAuth
> Upgrade django-cyverse-auth from 1.1.6 to 1.1.7

- CHANGELOG.md
- atmosphere/settings/local.py.j2
- jetstream/tas_api.py
- jetstream/test_tas_api.py
- jetstream/tests/test_user_validation.py
- variables.ini.dist
The previous pr https://github.com/cyverse/atmosphere/pull/639 did not actually work. 
- `TACC_API_TIMEOUT` was being templated as a string, rather than a number
- The exception raised during a timeout didn't result in offline validation of a users allocation
I tested this locally and fixed the issues. I additionally changed the scope so that the timeout only applies to GETs, I adjusted the variable so that its scope is obvious. Changed `TACC_API_TIMEOUT` to `TACC_READ_API_TIMEOUT`.
- https://github.com/cyverse/clank/pull/278
> Fix several issues in attempt to add timeout to tas api

- CHANGELOG.md
- service/tasks/__init__.py
Tasks reported as unregistered
Re-include imports in service.tasks.__init__.py
When these imports were removed (reported as unused) celery became unable to
auto-discover the tasks defined there.
It's not clear to me how to properly fix this. Will need to look into a proper fix later.
> Fix unregistered tasks

- CHANGELOG.md
- service/instance.py
Unshelving on IU would return nginx gateway timeout error
Remove unnecessary cloud check
This check queries all the instances in the cloud. It blocks requests to unshelve. If the query takes 30 sec, then the request to unshelve takes at least 30 sec.
On IU, the query takes a minute. This is way too long for a single api request. If 24 people tried to unshelve the entire app would be hung. nginx was timing out for unshelving instances on IU because of how long this took, with a Gateway Timeout Error.
> Remove expensive cloud check on unshelve

- CHANGELOG.md
- service/instance.py
When an instance was missing a floating ip, Nova would report "floating IP not found", we attempted to handle that case, by checking if the string matched "floating ip not found". They don't match so the exception would surface.
Rather than performing frail checks, just try and give up.
> Fix exception handling preventing instance destroy

- service/allocation_logic.py
Solution: Check for 'basestring' instead of 'str'
> Problem: Rate validation function fails for unicode

- atmosphere/settings/local.py.j2
Using SERVER_NAME to format the ATMO_DAEMON variable caused emails to be sent from atmo-notify@atmo.cyverse.org, but they should come from atmo.cyverse.org.
Also removed '<>' from the email string because these are added by Atmosphere before sending the email.
> Change ATMO_DAEMON variable to be formatted with DEFAULT_EMAIL_DOMAIN

- CHANGELOG.md
- api/v2/views/image.py
Simply add the 'description' field of the Application/Image model to the `search_fields` attribute of the ImageViewSet.
> Add description to image search fields

- CHANGELOG.md
- cyverse_allocation/cyverse_rules_engine_setup.py
- cyverse_allocation/plugins/allocation_source.py
- features/allocation.features/alternate_story.feature
- run_tests_like_travis_docker.sh
- variables_for_testing_cyverse_docker.ini.patch
- variables_for_testing_jetstream_docker.ini.patch
Increased the default renewal Allocation Units from 168 to 336.
> Increase default renewal AUs from 168 to 336.

- CHANGELOG.md
- Dockerfile
Since production deployments of Atmosphere Docker will not mount local code volumes, atmosphere-ansible needs to be built-in to the image. This adds a line to shallow clone the repository. Note this is built off of #704 and includes those commits
> Include atmosphere-ansible in Dockerfile build

- CHANGELOG.md
- Dockerfile
- dev_requirements.txt
- docker/entrypoint.sh
- requirements.txt
When testing the new deploy of v36-0, email was failing to send since sendmail was not installed.
Additionally, after imaging requests would complete, an error would occur from python-ldap. [This issue](https://github.com/python-ldap/python-ldap/issues/226) revealed it was a bug in version 3.1.0.
> Fix python-ldap and install sendmail in Docker

- CHANGELOG.md
This PR just updates the changelog to reflect the v36-1 minor release with fix to python-ldap version and sendmail in Docker
> Update changelog to release v36-1

- CHANGELOG.md
- api/v2/views/instance.py
Jetstream users noticed that, when using atmosphere-cli, they were able to specify a project UUID when launching an instance that did not belong to the user launching the instance. This PR fixes this by adding `created_by_id=user.id` when querying for the project. This will raise a `DoesNotExist` exception in the case that a project with specified UUID **and** creator ID does not exist. I was able to test this locally using a project ID owned by a different user to get this output:
```
ERROR: {u'errors': [{u'message': u'Project matching query does not exist.', u'code': 409}]}
Error, instance not created! Make sure to supply name, identity, project, size, source (or image), and allocation_source.
```
~Projects are owned by a Group and created by a AtmosphereUser. I chose to check the …
> JETSTREAM-240: Don't allow users to create Instances in Projects they do not own

- dev_requirements.txt
- requirements.txt
This completes the dependency upgrades for Atmosphere. After creating a new version of `jwt.py` on PyPI, I had to run `pip-compile -P jwt.py requirements.in` in order to get the latest version of `jwt.py` since it is from `django-cyverse-auth` requirements with unspecified version. Without this command, `pip-compile` would avoid changing to the latest version since it was not explicitly required.
> Update jwt.py dependency from django-cyverse-auth

- core/models/user.py
When attempting to login into the /admin/ page on localhost, a NotImplementedError was thrown as a subclass of the AbstractBaseUser did not contain the necessary get_short_name() function. This turned out to be a function omitted from user.py and has now been added. 
To reproduce:
1. Go to the admin page
2. Enter login credentials. *Error should appear after you press Log In.*
> Add get_short_name() function patching NotImplementedError at /admin/

- CHANGELOG.md
- core/models/machine_request.py
Jetstream encountered an error when a user with username ending in 'u' tried to create a private image. The `get_access_list()` method replaces `u"` of unicode strings which also replaced the 'u' at the end of the username. This is a simple fix that just replaces `u"` before swapping all `'` with `"`
> Fix bug in 'machine_request.get_access_list()'

- CHANGELOG.md
- dev_requirements.txt
- requirements.in
- requirements.txt
> Update to Django 1.11.23

- CHANGELOG.md
- scripts/jetstream/enforce_special_allocation_quota.py
- scripts/jetstream/enforce_special_allocation_quota.sh
- scripts/jetstream/ezb_users_over_allocation.sh
- scripts/jetstream/ezb_users_over_allocation.sql
One of the Jetstream cron scripts relies on a similarly-named python script and another one relies on an sql file. This PR adds the python script and sql file and edits the shell scripts to use the new paths.
> Add more Jetstream-specific scripts

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
Update chromogenic to latest version
> Update Chromogenic version

- .travis.yml
`setuptool` 45.0 and beyond seems to break under python 2
> specify setuptools version for python 2

- CHANGELOG.md
- api/v2/views/instance.py
- service/exceptions.py
- service/instance.py
- service/quota.py
Enable launching multiple instances with a single request.
Multi-instance launch request is just the normal launch request with an extra parameter.
e.g.
```
{
"extra": {"instance_count": 2}
}
```
> Multi instance launch

- docker/uwsgi.ini
This will allow us to use 'extra_hosts' in docker-compose to map the `atmosphere` hostname to any IP we want (which will be 127.0.0.1)
> Use 'atmosphere' as host for uwsgi listener

- CHANGELOG.md
- service/tasks/driver.py
Reduce number of retry and timeout on the celery task that runs the deployment ansible. The original retries count is too redundant because there is additional retries in Argo workflow that that tasks invoke. The change will allow deployment that cannot succeed to show up as failed quicker.
> Reduce deploy retry

- CHANGELOG.md
- dev_requirements.txt
- docker/entrypoint.sh
- requirements.in
- requirements.txt
- service/deploy.py
- bump ansible version to 2.8
- calls `ansible-playbook` executable directly rather than via the ansible python library
> bump ansible version to 2.8
