cyverse/atmosphere

- api/v2/serializers/details/project.py
- api/v2/views/image.py
- api/v2/views/mixins.py
- api/v2/views/project.py
Add support for looking up objects by there id, uuid or by another field name.
> add multiple field lookup mixin

- api/v2/serializers/details/__init__.py
- api/v2/serializers/details/volume.py
- api/v2/serializers/summaries/identity.py
- api/v2/views/volume.py
- service/exceptions.py
- service/volume.py
* Implement  volume creation.
* Implement volume  updating. 
* Implement volume deletion with cascade deletion support.
* Update service exceptions to use new base exception `ServiceException`
* New `VolumeError` exception for volume errors.
* New `NotFound` exception for resources that are not found.
> Implement Volume v2

- api/v1/views/email.py
- core/email.py
Feedback, Instance and Volume reports all expect 'user-interface' and write in the server before sending emails.
Tested and verified that emails appeared as expected on my dev server.
> Add 'e-mail tracking' to the E-mail support APIs

- api/v2/views/email.py
This fixes the 404 that results from clicking feedback/support at the bottom.
This needs to be cherry-picked into master.
> Fix calls to feedback/support

- requirements.txt
**Note:** this will need to be picked into kicking-kestrel
> Pull in rtwo that fixes setting provider quota

- api/v1/views/instance.py
This brings over 3 commits from #84.
> Provided functionality from #84 as a patch to kicking-kestrel

- service/management/commands/celery_start.py
- service/management/commands/start_celery.py
Celery can now be started using `python manage.py start_celery`
Logs will be output to "celery_node.log" in the current working directory
> Add celery script

- api/v2/views/base.py
- api/v2/views/machine_request.py
- service/machine.py
Hot new feature: Add to the request's access list if it exists instead of completely ignoring it.
Also add user groups from that access list to `new_version_membership`
> Jetstream machine request fixes

- api/v2/views/metric.py
The cache lookup did not take into account the instance uuid, when fetching
the instance's datapoints. The cache would return the latest datapoints for a
similar request made to any instance.
My reaction: (. _.) -> (0  .  @)
> Fix: users see each others graphs

- api/v2/views/metric.py
There was a hasty commit to fix this cache error. I reverted it for historical reference and added the proper fix.
> Fix cache error, where users see incorrect graphs

- api/renderers.py
- atmosphere/settings/__init__.py
- core/models/abstract.py
- core/models/application.py
- core/models/application_tag.py
- core/models/application_version.py
- core/models/identity.py
- core/models/instance.py
- core/models/instance_source.py
- core/models/machine.py
- core/models/machine_request.py
- core/models/profile.py
- core/models/project_application.py
- core/models/project_instance.py
- core/models/project_link.py
- core/models/project_volume.py
- core/models/ssh_key.py
- core/models/status_type.py
- core/models/t.py
- requirements.txt
The `__unicode__` method makes it easier to determine information about the objects you are looking at in Django. A lot of core models were missing this method, in those instances I chose the most useful information to display per resource.
> Add __unicode__ for all core models

- scripts/admin_update_password.py
- service/accounts/openstack_manager.py
> Change password hashing method + new admin script for changing passwords in bulk

- api/v2/views/instance.py
Fix for [ATMO-1299](https://pods.iplantcollaborative.org/jira/browse/ATMO-1299).
> API v2 POST instance error handling

- allocation/models/strategy.py
- api/v1/views/email.py
- api/v2/views/email.py
- atmosphere/settings/__init__.py
- core/admin.py
- core/email.py
- core/models/__init__.py
- core/models/application_version.py
- core/models/instance.py
- core/models/instance_history.py
- core/models/machine.py
- core/models/machine_request.py
- core/models/user.py
- requirements.txt
- scripts/generate_metrics.py
- service/accounts/openstack_manager.py
- service/deploy.py
- service/instance.py
- service/quota.py
- service/tasks/monitoring.py
- service/tasks/volume.py
- service/volume.py
> Final merge from divergent branch

- api/v2/views/email.py
A bug slipped through passing the `data` keyword argument to a function that no longer accepted it. Also InstanceReport request tracker now includes RT.
All three email requests were tested with success in troposphere. In the old UI, feedback was tested.
> [ATMO-991] Update html emails

- atmosphere/celery_router.py
- atmosphere/settings/__init__.py
- core/models/abstract.py
- core/models/allocation_strategy.py
- core/models/application.py
- core/models/application_tag.py
- core/models/cloud_admin.py
- core/models/instance.py
- core/models/instance_source.py
- core/models/machine.py
- core/models/volume.py
- service/tasks/monitoring.py
First there was monitor_instances.. Then machines.. and sizes.. This was the next logical step and will break us from our "Old cloud pulling ways" :rainbow:
> Monitor Volumes

- README.md
- contrib/configure-warning.sh
- contrib/post-merge.hook
I also fixed some of the docs on symlinking the hooks.
> Add hook to test if configure should be run

- api/tests/v2/test_tags.py
- core/tests/models/test_event_table.py
- jetstream/fixtures/README.txt
- jetstream/test_tas_api.py
- jetstream/tests.py
- run_tests.sh
- test_utils/cassette_utils.py
Replaces: PR https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/191
> Fix failing tests & add new EventTable tests

- service/accounts/openstack_manager.py
- service/networking.py
We made some incorrect assumptions about the external network strategy.
After some amount of clarification, these are the changes that were required in order to get ExternalNetwork support setup.
> Updates to ExternalNetwork strategy

- api/v1/serializers/profile_serializer.py
- atmosphere/plugins/auth/expiration.py
- core/models/user.py
- core/plugins.py
> Create an Expiration Plugin for LDAP

- api/v2/views/base.py
- api/v2/views/machine_request.py
- core/templates/core/email/imaging_request_staff.html
…of the e-mail. 
Additionally, Update the v2 APIs to respect /approve and /deny for /v2/machine_request endpoints
> Update imaging_request email to fix errors in staff section

- service/instance.py
Update the 'restore_ip_chain' to set the instance to 'Initializing' *before* any other actions take place to avoid _bounce-back_ from the API
Troposphere PR: https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/484
> Fix API to include 'initializing' when calling 'restore IP chain'

- api/v2/views/image_bookmark.py
The bookmark queryset was incorrect it had a filter that was returning an
empty list.
> Fix disappearing image bookmarks on refresh

- README.md
- scripts/print_broken_instances.py
@steve-gregory the instructions to run this script could be improved, what do you suggest?
> This script will print instances in networking or deploy_error

- extras/logrotate.atmosphere
- extras/logrotate.celery
> Use date extension file naming for logrotate for easy archiving.

- PULL_REQUEST_TEMPLATE.md
A PR template was requested as part of the improvements to the contribution and development process of Atmosphere.
Included is a sample PR template for consideration.
> Create PULL_REQUEST_TEMPLATE.md for Atmosphere

- service/exceptions.py
- service/instance.py
... for errors that occur during runtime in the preliminary stages of instance launch. 
Previously, such errors would return a 409 and would not provide any exception message.
> Provide a hotfix to display helpful, human readable errors and status codes

- requirements.txt
- service/tasks/driver.py
- service/tasks/machine.py
These changes were created on (jetstream) production and have forced it to fall out of sync with the v release.
> Jetstream Changes

- service/quota.py
> Problem: `set_provider_quota` did not return a complete set of results.

- .gitignore
- setup.cfg
Making my life easier when using Coverage by fixing these:
- Coverage files show up as untracked in Git working directory.
- Coverage report includes libraries in virtual environment.
~~- [ ] New test(s) included to reproduce the bug/verify the feature~~
> Tweak environment for Coverage

- api/tests/v2/test_identities.py
- api/v1/serializers/maintenance_record_serializer.py
- api/v2/views/image_version_boot_script.py
- api/v2/views/image_version_license.py
- api/v2/views/image_version_membership.py
- api/v2/views/instance_action.py
- api/v2/views/instance_history.py
- api/v2/views/volume.py
- atmosphere/__init__.py
- atmosphere/celery_init.py
- atmosphere/celery_router.py
- atmosphere/settings/__init__.py
- atmosphere/settings/testing.j2
- atmosphere/wsgi.py
- extras/init.d/celeryd.default.dist
- extras/init.d/celeryd.default.dist.j2
- extras/init.d/ubuntu.celeryd
- extras/uwsgi/atmo.uwsgi.ini.j2
- requirements.in
- requirements.txt
- service/accounts/openstack_manager.py
- service/deploy.py
- service/instance.py
- service/task.py
Upgrading to these packages caused a range of small issues.
This commit will fix those lingering issues. Be sure to REMOVE ALL PYC on rebuild
> Upgrade to Django1.10.x, Celery 4.x, latest of DRF and django-filter

- CHANGELOG.md
- api/v2/serializers/details/instance_action.py
- api/v2/views/image_version_boot_script.py
- api/v2/views/image_version_license.py
- api/v2/views/image_version_membership.py
- api/v2/views/instance_action.py
- api/v2/views/instance_history.py
- core/migrations/0071_provider_more_instance_actions.py
- core/models/instance_action.py
- core/models/managers.py
- core/models/provider.py
- Include 'Redeploy' as an instance action.
- Include 'Shelve' as an instance action when instance is in `active - <None>` state.
- Include 'Redeploy' + 'Restart' + 'terminate' commands when an instance is in `active - [networking, deploying, ...]` to keep consistency with previous iteration.
> Fixes to instance actions

- api/v2/serializers/details/ssh_key.py
- service/accounts/openstack_manager.py
- service/machine.py
- service/tasks/machine.py
- Fix to imaging: Updated access list on cloud provider works as expected.
- Fix SSHKeySerializer from throwing errors.
- Typo in ENABLE_IMAGE_VALIDATION task chain creation fixed.
> Small bugfixes from jetstream-cloud

- api/tests/factories/__init__.py
- api/tests/factories/leadership_factory.py
- api/tests/factories/project_instance_factory.py
- api/tests/factories/size_factory.py
- api/tests/v2/test_instance_actions.py
- api/tests/v2/test_project_instances.py
- api/tests/v2/test_sizes.py
- api/v2/views/instance.py
- api/v2/views/project_instance.py
- core/models/identity.py
- service/driver.py
- service/instance.py
- service/mock.py
- service/tasks/driver.py
Adding a new test script for `api/v2/project_instances/##`.
Adding a new test script for `api/v2/sizes/`
Adding a new test script for `api/v2/instances/##/actions`
> WIP: Add some new test scripts

- requirements.txt
- service/deploy.py
Ansible 2.3 brings some pretty awesome new features, including:
* Persistent connections framework
* See https://github.com/ansible/ansible/blob/stable-2.3/CHANGELOG.md for more
* Requires an update to subspace, 0.4.1
* Updated log format, example:
```
AnsibleDeployException: failed with PlayBook(s) => {('Playbook: /opt/dev/atmosphere-ansible/ansible/playbooks/instance_deploy/20_atmo_user_install.yml', u'Role: atmo-common', u'Task: Update timezone'): {'failures': 1}}
```
> Updated atmosphere to latest subspace, ansible 2.3

- api/v1/views/instance.py
- api/v2/serializers/post/instance.py
- api/v2/views/instance.py
- atmosphere/settings/__init__.py
- atmosphere/settings/local.py.j2
- core/models/allocation_source.py
- core/models/instance.py
- jetstream/tasks.py
- service/exceptions.py
- service/instance.py
- service/monitoring.py
- service/tasks/monitoring.py
- variables.ini.dist
Remove all traces of USE_ALLOCATION_SOURCES -- Addresses #342
> Problem: settings.USE_ALLOCATION_SOURCES should be removed

- CHANGELOG.md
updated changelog for X-X release
> CHANGELOG updated

- api/v2/views/reporting.py
- service/tasks/driver.py
These one-off changes were uncommitted and are being included prior to the deployment.
> Update reporting API + fix args on remove_ips

- core/models/instance.py
- core/models/instance_action.py
These changes were required to show more accurate instance actions for shelve/unshelve.
> Update instance actions and history to enable Shelve/Unshelve

- CHANGELOG.md
- core/models/instance_action.py
- jetstream/features/create_report_test_after_user_deleted.feature
- jetstream/features/steps/create_report_test_after_user_deleted.py
- jetstream/tasks.py
- requirements.txt
- service/tasks/machine.py
Keep `allocations` up to date with `x-x` or we will suffer.
> Merge `x-x` into `allocations`

- service/tasks/monitoring.py
Problem: Found unused function in my travels. And it's also broken.
Solution: Delete it! ␡
> Problem: Found unused function in my travels. And it's also broken.

- api/tests/factories/__init__.py
- api/tests/factories/instance_history_factory.py
- api/v2/serializers/details/allocation_source.py
- atmosphere/plugins/quota/default_quota.py
- atmosphere/settings/local.py.j2
- core/hooks/allocation_source.py
- core/models/user.py
- core/plugins.py
- dev_requirements.in
- dev_requirements.txt
- features/allocation.features/commands.feature
- features/allocation.features/enforcing.feature
- features/environment.py
- features/jetstream.features/enforcing.feature
- features/jetstream.features/special_allocation.feature
- features/steps/allocation_steps.py
- features/steps/api_with_persona_steps.py
- features/steps/steps.py
- features/steps/tas_api_steps.py
- jetstream/plugins/quota/default_quota.py
- jetstream/tests/tas_api_mock_utils.py
- service/allocation_logic.py
Problem: Need 'sub'-allocations which have reduced quota & allocation
Solution:
> Problem: Need 'sub'-allocations which have reduced quota & allocation

- core/hooks/allocation_source.py
- core/models/allocation_source.py
- core/models/event_table.py
- core/models/instance.py
- service/exceptions.py
- service/instance.py
- service/monitoring.py
- service/tasks/monitoring.py
Rebased @steve-gregory's branch on new cyverse/allocations to fix some conflicts.
> Allocations enforcement

- core/migrations/0082_create_allocationsource_for_users.py
Redundant migration run prevented
> Redundant migration problem

- service/monitoring.py
Solution: Use correct variables. Also added more logging.
> Problem: Undefined variables in _execute_provider_action

- api/v2/views/web_token.py
- atmosphere/settings/local.py.j2
- variables.ini.dist
... from views/guacamole (in troposphere) to the web_tokens API as
created for web desktop.
- https://github.com/cyverse/troposphere/pull/639
- https://github.com/cyverse/atmosphere-ansible/pull/78
- https://github.com/cyverse/clank/pull/167/
> (with @calvinmclean) Guacamole Integration (web_token)

- CHANGELOG.md
- requirements.in
- requirements.txt
- scripts/application_to_provider.py
Feedback from @steve-gregory. Depends on #318, please merge that first.
>  Moving code that obtains a Glance client into its own function

- core/models/quota.py
Solution: Don't assume port has a project_id, and use a default.
> Problem: Instances fail to launch on Havana due to API change

- PULL_REQUEST_TEMPLATE.md
When I changed some variables for a release, someone had to guess what the proper values were during deploy. The wrong values were inserted. I'm adding a small reminder in the template, so the person creating the variable will set the variable.
> Add requirements for new variables

- dev_requirements.txt
- requirements.in
> Use requirements.in to specify dependencies

- dev_requirements.txt
- requirements.in
- requirements.txt
Re-run pip-compile prior to mock deployment before the release of our second production system.
> Update requirements for zesty

- scripts/add_new_accounts.py
Solution: Removed what seemed like a redundant `else`
> Problem: Invalid Python syntax in `add_new_accounts.py`

- core/models/group.py
Original intent of the method can be found here:
https://github.com/cyverse/atmosphere/commit/6fada56c4b8a14164d298e9decaee4f74bd22fc8#diff-c8839ecd9fe07f17d5801140a2e775acL230
> Fix to 'IdentityMembership.is_member'

- scripts/application_to_provider.py
Migrates/updates image metadata only, not image data.
Useful for the case where a private application was previously migrated before all the image members on source provider were added as projects on the destination provider. Running this with --metadata-only afterward would add the remaining members to the image on the destination provider, allowing those members to launch instances from the application.
> --metadata-only option for application_to_provider

- scripts/application_sync_providers.py
> redacting iRODS credentials from log output

- service/accounts/openstack_manager.py
- service/instance.py
- service/networking.py
**jmlowe commented on Sep 9, 2016**
> Starting with the kilo release neutron can use a shared subnet pool,
this ensures unique subnets without the need to probe. When a subnet
pool id is configured skip the search and CIDR specification and just
create the subnet using the subnet pool.
> This may need some further polish, I took the per provider override for settings at face value. One possible improvement would be to use subnet pool name and lookup the id.
**Required before merge:**
> Include subnet pool specification with a default of None

- .travis.yml
- dev_requirements.in
- dev_requirements.txt
- requirements.txt
- travis/check_properly_generated_requirements.sh
- travis/files_added.sh
- travis/files_changed.sh
- travis/lint.sh
Introducing linting into a project can be tricky. This script runs a strict variant on newly added files, and a lenient variant on modified files. This is a win for two reasons:
- New code will be  💅 
- Old code will gradually become 💅 
The linting tool is [prospector](https://prospector.landscape.io/en/master/). It has a lot of common sense defaults, and bundles pyflakes/pylint and others. It supports vulture as a plugin so we can nuke all our dead code.
> Introduce linting 💅

- travis/check_properly_generated_requirements.sh
When comparing requirements strip out comments
Make requirements check spit out diffs when they exist
> Cherry-pick requirements improvements

- api/auth.py
- api/v1/views/token.py
- api/v2/views/emulate.py
- dev_requirements.txt
- requirements.txt
Solution: Update to django-cyverse-auth 1.1.0
Imports and methods have changed, so atmosphere needs to be updated accordingly.
> Problem: Race conditions in django-cyverse-auth negatively affecting application

- api/permissions.py
- api/v1/views/instance.py
- api/v2/views/instance.py
- api/v2/views/user_allocation_source.py
- core/models/instance.py
- service/deploy.py
- service/instance.py
Lots of small fixes. See individual commits.
> Small bug fixes

- dev_requirements.txt
- requirements.txt
Solution: Updated requirements
> Problem: Out of date requirements

- api/v2/views/instance.py
> Deploy by default

- dev_requirements.txt
- requirements.in
- requirements.txt
This brings in the necessary hotfix for django-cyverse-auth get_or_create_[token|user]
> Use hotfix in django-cyverse-auth@62bd28012

- dev_requirements.in
- requirements.in
- requirements.txt
Solution: Move `newrelic` from `dev_requirements.in` to `requirements.in`
> Problem: New Relic not installed in production

- core/models/volume.py
- service/volume.py
Solution: remove 'start_date' from Volume. (Start_date set in InstanceSource)
> Problem: POST to /v2/volume returns "'start_date' is an invalid keyword argument for this function"

- .travis.yml
- README.md
- setup.cfg
Solution: Use Coveralls with Travis
> WIP - Problem: Not keeping track of test coverage

- README.md
Solution: Added missing contributors and use `cyverse.org`
> Problem: Contributors incomplete and using old domain

- dev_requirements.txt
- requirements.txt
> Bump rtwo 0.5.12 -> 0.5.13 (Support pagination from Nova API)

- PULL_REQUEST_TEMPLATE.md
Companion to [clank PR #210](https://github.com/cyverse/clank/pull/210).
> Updating PR template with todo item for updating sanitation queries when appropriate

- service/monitoring.py
Solution: Added parameter back which recently went missing.
> Problem: Missing `user` param

- .travis.yml
- dev_requirements.in
- dev_requirements.txt
Move coveralls dev dependency into dev_requirements
> Move coveralls into dev reqs

- api/v2/serializers/details/resource_request_actions.py
This is a hack.
Problem:
In j7m, users don't make resource requests against specific
providers, yet each request is tied to a provider (identity). So admins in j7m
are approving quota essentially for one (random) identity of the user's identities.
Solution:
In the action for changing quota (specific to resource requests)
update the quota for all the user's identities.
> V27 fix broken jetstream admin quota update

- atmosphere/settings/local.py.j2
- atmosphere/wsgi.py
Solution: Provide optional support for new relic via template
> Problem: New relic must be added after template configuration

- service/instance.py
- service/monitoring.py
- service/tasks/driver.py
This is a HACK!
- Set to False if the provider is 'iPlant Cloud - Tucson'
- all other providers set to True (The default operation for all clouds)
> Quickfix for setting reclaim_ips

- core/admin.py
- core/models/volume.py
See commits
~- [ ] New test(s) included to reproduce the bug/verify the feature~
~- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~
~- [ ] If creating/modifying DB models which will contain secrets or sensitive information, PR to [clank](https://github.com/cyverse/clank) updating sanitation queries in `roles/sanitary-sql-access/templates/sanitize-dump.sh.j2`~
~- [ ] If necessary, include a snippet in CHANGELOG.md~
~- [ ] New variables supported in Clank~
~- [ ] New variables committed to secrets repos~
> Fixes from prod

- jetstream/admin_panel/tas_api_panel.py
Solution: Handle this case properly. Also removed copy-pasta.
> Problem: Server error when TAS API result is `None`

- api/v1/urls.py
- api/v1/views/size.py
- atmosphere/settings/local.py.j2
- extras/nginx/locations/atmo.conf.j2
- variables.ini.dist
Bugs fixed and improvements listed below:
- Fix /v1/..../size detail endpoint
- Allow lookup by size alias (previous methods were failing and throwing 500)
- ... of 500 error emails when debug=False
- Include 'localhost' to the ALLOWED_HOSTS to allow easy access to debugging...
- ... and enable '/dev' location in nginx to pass calls to runserver standard port.
> Small Bugfixes and QOL improvements

- core/models/machine.py
> Problem: monitor machines fails due to missing kwargs

- api/v2/views/resource_request.py
> Problem: Unused variable

- run_tests_like_travis.sh
Just some small tweaks to `run_tests_like_travis.sh`. Thanks for writing this @julianpistorius.
> Run tests as travis improvements

- CHANGELOG.md
> Updated `CHANGELOG.md` for v30

- core/models/instance_action.py
Solution: Remove the imaging action for the following state(s):
- 'active - deploy_error'
- 'shelved_offloaded'
- 'shelved'
> Problem: Imaging action available for invalid states

- LICENSE.txt
> Update LICENSE.txt to 2018

- README.md
:coffin: RIP -- Thanks for all the memories! :wave:
> Steve-Gregory -> Cloud alum

- features/allocation.features/alternate_story.feature
See 99c717261aa292432e974ffc92d0b85d93b8bec2 for the exact same issue
> Fix test breaking because of implicit dependency on current time

- CHANGELOG.md
> Cut v32-1 release, and minor fixes to changelog markdown

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
- service/accounts/openstack_manager.py
Upgrade to rtwo 0.5.18 (ignore the branch name)
> Upgrade to latest rtwo

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
rtwo 0.5.20 was not uploaded correctly, need to use the latest version
> Upgrade to rtwo 0.5.21

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
See https://github.com/cyverse/rtwo/pull/31
> Fix issue where rtwo pagination resulted in failing to retrieve all instances

- CHANGELOG.md
- atmosphere/settings/local.py.j2
Bump task times which were timing out
> Bump task times which were timing out

- service/tasks/machine.py
Imaging failed because it was still using the old arguments for 'execution_has_failures' and 'execution_has_unreachable'.
> Fix the usage of new deployment process in the imaging tasks

- CHANGELOG.md
- api/tests/v2/test_instances.py
- api/v2/views/instance.py
The v2 api delete endpoint was never really tested when it was implemented. It was missing a few things. See my commit messages.
> Fix api v2 delete

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
Upgrade to chromogenic==0.4.20
> Upgrade to chromogenic==0.4.20

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
See https://github.com/cyverse/django-cyverse-auth/pull/32
> Add support for CAS 5

- CHANGELOG.md
- Dockerfile
- docker-compose.test.yml
- docker/README.md
- docker/celerybeat.initd
- docker/celeryd.initd
- docker/entrypoint.sh
- docker/flower.initd
- docker/ssh.config
- docker/test.sh
- docker/uwsgi.ini
- docker/web_shell_no_gateone.yml
Adding a Dockerfile to the source repository has a few benefits:
- The container is now closely associated with code that it is meant to run which is more standard
- Makes automated build/test easier
- Allows Dockerhub to automatically create image versions based off tags and PRs
- Allows requirements.txt to be installed during build process to save startup time
After this PR is merged, the following rules can be added to a Dockerhub automated build/test:
| Source               | Docker Tag     | Matches        |
| :------------------- | :------------- | :------------- |
| `/^v[0-9]+$/`        | `{sourceref}`  | `v36`          |
| `/^v[0-9]+-[0-9]+$/` | `{sourceref}`  | `v36-0`        |
> Add Dockerfile and automated testing files

- CHANGELOG.md
Update changelog to show new v36-0 release
> Release Atmosphere v36-0

- CHANGELOG.md
Update changelog for release v36-2
> Update CHANGELOG for v36-2

- CHANGELOG.md
Fix some bugs for v36-3 (see changelog)
> Update CHANGELOG for v36-3

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
This PR just changes rtwo to the latest version that fixes [this bug](https://github.com/cyverse/rtwo/issues/39)
> Update rtwo requirement

- CHANGELOG.md
- scripts/jetstream/cron_application_sync_providers.sh
- scripts/jetstream/enforce_special_allocation_quota.sh
- scripts/jetstream/ezb_users_over_allocation.sh
Adding the Jetstream specific scripts to version contorl so they don't go missing.
> Add Jetstream specific scripts

- CHANGELOG.md
- dev_requirements.txt
- requirements.txt
Upgrade to Chromogenic 0.5.3
This fixes an error that caused imaging failure on CentOS 7 images
> Upgrade Chromogenic to 0.5.3

- CHANGELOG.md
Update changelog for v36-5 release
> Release v36-5 in changelog

- CHANGELOG.md
> release v36-3

- .travis.yml
- CHANGELOG.md
- scripts/application_to_provider.py
- scripts/end_date_volumes_invariant_13a.py
- scripts/fix-deb.sh
- scripts/jetstream/cron_end_date_volumes_invariant_13a.sh
- scripts/jetstream/cron_shelve_instances_invariant_12.sh
- scripts/shelve_instances_invariant_12.py
Modify application_to_provider.py, which is used by application_sync_provider.py in order to sync images from one provider to another (currently IU to TACC).
> Jetstream changes and additions to scripts directory

- CHANGELOG.md
- docker/entrypoint.sh
- service/argo/common.py
> Release v37-0

- CHANGELOG.md
- scripts/jetstream/switch_user_quota.sh
- scripts/switch_user_quota.py
Added a script to switch user's quota to a different one on a given provider.
> script to switch user's quota to different one

- CHANGELOG.md
- scripts/celery_watcher.sh
> add celery_watcher.sh

- CHANGELOG.md
> update changelog for v37-2

- CHANGELOG.md
- service/argo/instance_deploy.py
- service/argo/wf.py
- add username & instance_uuid label to workflow
> add username & instance_uuid label to workflow

- CHANGELOG.md
- Dockerfile
> install wget in Docker image

- CHANGELOG.md
> update changelog for v37-4
